const {
  ChargerRepository,
  ChargerConnectorTypeRepository,
  ChargerUsageTypeRepository,
} = require("@shared-libs/db/mysql");

const SeedChargers = async () => {
  try {
    const chargerData = await ChargerRepository.find();

    if (chargerData.length === 0) {
      const chargeUsageType = await ChargerUsageTypeRepository.findOne({
        where: { mappingText: "public" },
      });
      const chargeUsageTypeId = chargeUsageType.id;

      const chargers = [
        {
          serialNumber: "DA2B0540ED844RF3",
          chargeBoxId: "CGX123424000026",
          deviceName: "DD",
          activationDate: "2024-09-04 13:17:32",
          registeredAt: "2024-09-04 12:27:55",
          lat: "20",
          lng: "70",
          validTill: "2027-09-04 13:17:32",
          status: "offline",
          activationCode: "gMPmEm",
          activationExpiresAt: "2024-09-13 06:30:30",
          activationRequestedAt: "2024-09-06 06:30:30",
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "1234",
          connectorPair: "",
          country: "",
          timezone: null,
          lastHeartbeat: "2024-09-05 05:36:49",
          chargingStatus: "Available",
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "DA2B0540ED844CF3",
          chargeBoxId: "CGX123424000025",
          deviceName: "DD",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "1234",
          connectorPair: "",
          country: "",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "DA2B0540ED844CF1",
          chargeBoxId: "CGX123424000024",
          deviceName: "DD",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "1234",
          connectorPair: "",
          country: "",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "DA2B0540ED844CF2",
          chargeBoxId: "CGX12324000023",
          deviceName: "DD",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "123",
          connectorPair: "",
          country: "",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "EF8B7A6883354E2B",
          chargeBoxId: "CGXPrime24000022",
          deviceName: "KL1",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: "0",
          lng: "0",
          validTill: null,
          status: "registered",
          activationCode: "5y2XQv",
          activationExpiresAt: "2024-09-13 06:26:08",
          activationRequestedAt: "2024-09-06 06:26:08",
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "Prime",
          connectorPair: "",
          country: "MY",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "4fdff95270d74053",
          chargeBoxId: "CGXPRGS24000096",
          deviceName: "Volt",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: "19.1109087",
          lng: "73.0287094",
          validTill: null,
          status: "registered",
          activationCode: "fUHKsW",
          activationExpiresAt: "2024-09-13 06:34:17",
          activationRequestedAt: "2024-09-06 06:34:17",
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: "GS",
          country: "US",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "cda5d63942b84a6d",
          chargeBoxId: "CGXPRGS24000095",
          deviceName: "Volt",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: "19.1109087",
          lng: "73.0287094",
          validTill: null,
          status: "registered",
          activationCode: "LULU7h",
          activationExpiresAt: "2024-09-11 10:41:36",
          activationRequestedAt: "2024-09-04 10:41:36",
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: "GS",
          country: "IN",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "SRN999789",
          chargeBoxId: "CGXPRGS24000094",
          deviceName: "SRN999",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: null,
          status: "registered",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: "GS",
          country: "IN",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "SRN997",
          chargeBoxId: "CGXPRGS24000109",
          deviceName: "SRN997",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: "19.1109088",
          lng: "73.0337095",
          validTill: null,
          status: "registered",
          activationCode: "G5ACw6",
          activationExpiresAt: "2024-09-12 07:55:56",
          activationRequestedAt: "2024-09-05 07:55:56",
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: "GS",
          country: "ID",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "SRN0000992",
          chargeBoxId: "CGXHPSG24000104",
          deviceName: "SRN0000992",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: null,
          lng: null,
          validTill: null,
          status: "offline",
          activationCode: "tqYvyO",
          activationExpiresAt: "2024-09-17 15:13:25",
          activationRequestedAt: "2024-09-10 15:13:25",
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "1234",
          connectorPair: "",
          country: "",
          timezone: null,
          lastHeartbeat: "2024-09-24 12:38:14",
          chargingStatus: "Available",
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "SRN0067",
          chargeBoxId: "CGXHPSG86944345",
          deviceName: "volt0067",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: null,
          status: "registered",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "1234",
          connectorPair: "",
          country: "",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "SRN0065",
          chargeBoxId: "CGXHPSG64844974",
          deviceName: "volt0065",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: "19.1109087",
          lng: "73.0366094",
          validTill: null,
          status: "registered",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "1234",
          connectorPair: "",
          country: "",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "SRN0063",
          chargeBoxId: "CGXHPSG23540268",
          deviceName: "volt0063",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: "19.1179087",
          lng: "73.0446094",
          validTill: null,
          status: "registered",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "1234",
          connectorPair: "",
          country: "",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "SRN0060",
          chargeBoxId: "CGXHPSG13052265",
          deviceName: "volt0060",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "1234",
          connectorPair: "",
          country: "",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "SRN0022",
          chargeBoxId: "CGXHPSG41945591",
          deviceName: "volt022",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "1234",
          connectorPair: "",
          country: "",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "SRN0021",
          chargeBoxId: "CGXHPSG21782271",
          deviceName: "volt021",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "1234",
          connectorPair: "",
          country: "",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "SRN0018",
          chargeBoxId: "CGXHPSG22724216",
          deviceName: "volt014",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "1234",
          connectorPair: "",
          country: "",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "SRN0013",
          chargeBoxId: "CGXHPSG27570478",
          deviceName: "volt013",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: "36.169942",
          lng: "-115.139832",
          validTill: null,
          status: "registered",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "1234",
          connectorPair: "",
          country: "",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "SRN008",
          chargeBoxId: "CGXHPSG52639910",
          deviceName: "volt08",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: "36.169942",
          lng: "-115.139832",
          validTill: null,
          status: "registered",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "1234",
          connectorPair: "",
          country: "",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "SRN006",
          chargeBoxId: "CGXHPSG30903684",
          deviceName: "volt06",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: "49.463731548984086",
          lng: "11.091751019115389",
          validTill: null,
          status: "registered",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "1234",
          connectorPair: "",
          country: "",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "SRN005",
          chargeBoxId: "CGXHPSG36031701",
          deviceName: "volt05",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: "49.44079429148874",
          lng: "11.090550894218548",
          validTill: null,
          status: "registered",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "1234",
          connectorPair: "",
          country: "",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "SRN004",
          chargeBoxId: "CGXHPSG98478075",
          deviceName: "volt04",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: "49.46638346461174",
          lng: "11.09655151870274",
          validTill: null,
          status: "registered",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "1234",
          connectorPair: "",
          country: "",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "SRN003",
          chargeBoxId: "CGXHPSG54419812",
          deviceName: "volt03",
          activationDate: null,
          registeredAt: "2024-09-04 12:27:55",
          lat: "49.45265434974534",
          lng: "11.075669345497756",
          validTill: null,
          status: "offline",
          activationCode: "RAKK2E",
          activationExpiresAt: "2024-09-17 15:13:15",
          activationRequestedAt: "2024-09-10 15:13:15",
          deviceAdminPassCode: 0,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "1234",
          connectorPair: "",
          country: "",
          timezone: null,
          lastHeartbeat: "2024-09-17 03:59:23",
          chargingStatus: "Preparing",
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          registeredBy: null,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "DC9310C4E79D4851",
          chargeBoxId: "CGXqwer24000024",
          deviceName: "qwe",
          activationDate: "2024-09-05 18:51:25",
          registeredAt: "2024-09-04 12:27:55",
          lat: null,
          lng: null,
          validTill: "2027-09-05 18:51:25",
          status: "activated",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 875508,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "qwer",
          connectorPair: "",
          country: "",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "C46C45EB90DF4245",
          chargeBoxId: "CGXPR24000025",
          deviceName: "NewCharger",
          activationDate: "2024-09-05 07:40:38",
          registeredAt: "2024-09-04 13:11:16",
          lat: null,
          lng: null,
          validTill: "2027-09-05 07:40:38",
          status: "activated",
          activationCode: "qJ0Txi",
          activationExpiresAt: "2024-09-13 06:33:53",
          activationRequestedAt: "2024-09-06 06:33:53",
          deviceAdminPassCode: 229528,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: "",
          country: "IN",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "B928C807591F4F28",
          chargeBoxId: "CGXPR24000026",
          deviceName: "New Charger Device",
          activationDate: null,
          registeredAt: "2024-09-06 06:49:26",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 784925,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: "",
          country: "BW",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "04193FB08739462E",
          chargeBoxId: "CGXPR24000027",
          deviceName: "Charger2 ",
          activationDate: null,
          registeredAt: "2024-09-09 05:00:21",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "pAZDaw",
          activationExpiresAt: "2024-09-17 15:12:49",
          activationRequestedAt: "2024-09-10 15:12:49",
          deviceAdminPassCode: 628059,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: "",
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: null,
        },
        {
          serialNumber: "6696E5445C1C447A",
          chargeBoxId: "CGXAQPRM202449B9D9",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-12 11:11:18",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "IEFicR",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 535029,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AQ",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "49B9D9",
        },
        {
          serialNumber: "8B8F5D327E4A4B27",
          chargeBoxId: "CGXBHPRM202476F979",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-12 12:03:13",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "QZSCrm",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 674480,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "BH",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "76F979",
        },
        {
          serialNumber: "74874AFADC4A445D",
          chargeBoxId: "CGXATPRM20247581C0",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-12 12:15:24",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "tMaKsi",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 766642,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AT",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "7581C0",
        },
        {
          serialNumber: "8726B9CA398C40DA",
          chargeBoxId: "CGXAUPRM202469B5A6",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-12 12:21:57",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "S0wiJE",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 355389,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "69B5A6",
        },
        {
          serialNumber: "3B39A82C81D64CD5",
          chargeBoxId: "CGXASPRM20248876CF",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-12 12:50:19",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "NY3QCn",
          activationExpiresAt: "2024-09-19 13:06:52",
          activationRequestedAt: "2024-09-12 13:06:52",
          deviceAdminPassCode: 871811,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AS",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "8876CF",
        },
        {
          serialNumber: "59C6911DC68342BF",
          chargeBoxId: "CGXATPRM20243985C6",
          deviceName: "NewCharger",
          activationDate: "2024-09-13 13:29:29",
          registeredAt: "2024-09-13 06:45:51",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-13 13:29:29",
          status: "activated",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 905913,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AT",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "3985C6",
        },
        {
          serialNumber: "528954541EC94D74",
          chargeBoxId: "CGXATPRM20241E44EA",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-13 07:12:28",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "ItaLL3",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 682616,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AT",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "1E44EA",
        },
        {
          serialNumber: "18A3E7B8AF7A4139",
          chargeBoxId: "CGXASPRM2024A7CF4F",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-13 08:47:25",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "5v4Eg7",
          activationExpiresAt: "2024-09-20 09:11:42",
          activationRequestedAt: "2024-09-13 09:11:42",
          deviceAdminPassCode: 501890,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AS",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "A7CF4F",
        },
        {
          serialNumber: "EB68A7A2413049AF",
          chargeBoxId: "CGXATPRM2024DBF4AB",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-13 09:25:47",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "StRzO7",
          activationExpiresAt: "2024-09-20 09:35:24",
          activationRequestedAt: "2024-09-13 09:35:24",
          deviceAdminPassCode: 655814,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AT",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "DBF4AB",
        },
        {
          serialNumber: "5BB3212EB67F431F",
          chargeBoxId: "CGXAFPRM2024D8AFFB",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-13 09:55:19",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "lshiSl",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 264281,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AF",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "D8AFFB",
        },
        {
          serialNumber: "035C0CEF9D414141",
          chargeBoxId: "CGXAFPRM20247C73FB",
          deviceName: "PR",
          activationDate: null,
          registeredAt: "2024-09-13 09:59:15",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "xLO5px",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 548573,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AF",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "7C73FB",
        },
        {
          serialNumber: "C049B8E490C14245",
          chargeBoxId: "CGXALPRM20241F205A",
          deviceName: "NewCharger",
          activationDate: "2024-09-13 10:54:31",
          registeredAt: "2024-09-13 10:14:05",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-13 10:54:31",
          status: "activated",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 260327,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AL",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "1F205A",
        },
        {
          serialNumber: "3ECA88BA3225412B",
          chargeBoxId: "CGXADPRM2024A712C9",
          deviceName: "KL1",
          activationDate: "2024-09-13 10:42:43",
          registeredAt: "2024-09-13 10:29:36",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-13 10:42:43",
          status: "activated",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 243023,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "Prime",
          connectorPair: null,
          country: "AD",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "cc2" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "A712C9",
        },
        {
          serialNumber: "8FB7F1D3531144D7",
          chargeBoxId: "CGXAMPRM2024490802",
          deviceName: "NewCharger",
          activationDate: "2024-09-13 13:09:57",
          registeredAt: "2024-09-13 13:09:30",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-13 13:09:57",
          status: "activated",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 729410,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AM",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "490802",
        },
        {
          serialNumber: "5FE2DE32E9864012",
          chargeBoxId: "CGXINPRM2024198813",
          deviceName: "Test device",
          activationDate: "2024-09-13 14:23:58",
          registeredAt: "2024-09-13 14:23:16",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-13 14:23:58",
          status: "activated",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 464989,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "Prime",
          connectorPair: null,
          country: "IN",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "198813",
        },
        {
          serialNumber: "FDD01DD9D48D4AEE",
          chargeBoxId: "CGXCAPRM202423F233",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-13 16:32:58",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "hfUHh8",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 533743,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "Prime",
          connectorPair: null,
          country: "CA",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "23F233",
        },
        {
          serialNumber: "8A928AFCFB0C41D8",
          chargeBoxId: "CGXCAPRM2024088EDC",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-13 16:35:24",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "0nMEEe",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 681461,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "Prime",
          connectorPair: null,
          country: "CA",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "088EDC",
        },
        {
          serialNumber: "9A6D5FE89CA04D4D",
          chargeBoxId: "CGXAUPRM2024F55D47",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-13 16:45:48",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "mBJPzo",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 831802,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "F55D47",
        },
        {
          serialNumber: "E16F8E31959D40F3",
          chargeBoxId: "CGXAUPRM2024514B24",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-13 16:47:25",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "wdnZzl",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 469792,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "514B24",
        },
        {
          serialNumber: "CC8AC20A77C84F25",
          chargeBoxId: "CGXAUPRM2024C7F5BA",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-13 16:47:56",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "Lvb8GW",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 794831,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "C7F5BA",
        },
        {
          serialNumber: "F1C5B198AFA44908",
          chargeBoxId: "CGXASPRM2024680916",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-13 17:11:35",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "W7xKS5",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 198956,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AS",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "680916",
        },
        {
          serialNumber: "149F73476E7A4429",
          chargeBoxId: "CGXAUPRM2024827D39",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-13 17:34:05",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "0bm8WO",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 746587,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "827D39",
        },
        {
          serialNumber: "EBEB7868D6124565",
          chargeBoxId: "CGXAustraliaPRM2024E2AF08",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-13 18:30:42",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "096x83",
          activationExpiresAt: "2024-09-20 18:30:54",
          activationRequestedAt: "2024-09-13 18:30:54",
          deviceAdminPassCode: 180982,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "E2AF08",
        },
        {
          serialNumber: "E988D059F3354811",
          chargeBoxId: "CGXAUPRM2024396B89",
          deviceName: "NewCharger",
          activationDate: "2024-09-13 18:47:47",
          registeredAt: "2024-09-13 18:46:46",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-13 18:47:47",
          status: "activated",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 865144,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "396B89",
        },
        {
          serialNumber: "ABF448F8E6C44CD8",
          chargeBoxId: "CGXAUPRM2024283755",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-13 18:51:16",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "o2ZPLY",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 847612,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "283755",
        },
        {
          serialNumber: "65EBF7530E5A4C92",
          chargeBoxId: "CGXAUPRM202486B17A",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-13 19:03:09",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "tNl7GG",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 242606,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "86B17A",
        },
        {
          serialNumber: "7CDBB71553C14E4E",
          chargeBoxId: "CGXAUPRM2024D34C66",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-13 19:06:19",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "yBdVTU",
          activationExpiresAt: "2024-09-20 19:06:27",
          activationRequestedAt: "2024-09-13 19:06:27",
          deviceAdminPassCode: 137889,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "D34C66",
        },
        {
          serialNumber: "EBED76921C4A4A95",
          chargeBoxId: "CGXAUPRM20243C06BF",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-13 19:15:29",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "1mivBV",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 864092,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "3C06BF",
        },
        {
          serialNumber: "B70777244A294227",
          chargeBoxId: "CGXATPRM2024C13E5A",
          deviceName: "VoltTest",
          activationDate: "2024-09-13 19:16:23",
          registeredAt: "2024-09-13 19:15:54",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-13 19:16:23",
          status: "activated",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 455913,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AT",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "C13E5A",
        },
        {
          serialNumber: "B0BADE4332BD46BE",
          chargeBoxId: "CGXAUPRM2024EDDBA3",
          deviceName: "NewCharger",
          activationDate: "2024-09-13 19:30:22",
          registeredAt: "2024-09-13 19:29:49",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-13 19:30:22",
          status: "activated",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 942931,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "EDDBA3",
        },
        {
          serialNumber: "3674B4F63ABC4CDF",
          chargeBoxId: "CGXAXPRM2024E747C2",
          deviceName: "NewCharger",
          activationDate: "2024-09-13 19:34:43",
          registeredAt: "2024-09-13 19:34:23",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-13 19:34:43",
          status: "offline",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 562717,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AX",
          timezone: null,
          lastHeartbeat: "2024-09-13 19:35:51",
          chargingStatus: "Available",
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "E747C2",
        },
        {
          serialNumber: "99E199AD85814728",
          chargeBoxId: "CGXINPRM20249DA337",
          deviceName: "Test device33",
          activationDate: "2024-09-14 02:43:19",
          registeredAt: "2024-09-14 02:42:35",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-14 02:43:19",
          status: "offline",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 584604,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "Prime",
          connectorPair: null,
          country: "IN",
          timezone: null,
          lastHeartbeat: "2024-09-14 02:44:16",
          chargingStatus: "Available",
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "9DA337",
        },
        {
          serialNumber: "0EE22CFCB7FE459E",
          chargeBoxId: "CGXAUPRM20244E7063",
          deviceName: "New Charger Device",
          activationDate: "2024-09-16 06:33:53",
          registeredAt: "2024-09-16 06:33:33",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-16 06:33:53",
          status: "activated",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 914305,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "Prime",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "4E7063",
        },
        {
          serialNumber: "C933CE02770A41AA",
          chargeBoxId: "CGXAUPRM202492718C",
          deviceName: "NewCharger",
          activationDate: "2024-09-16 06:47:43",
          registeredAt: "2024-09-16 06:47:25",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-16 06:47:43",
          status: "activated",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 223651,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "92718C",
        },
        {
          serialNumber: "374FE5F0515C4382",
          chargeBoxId: "CGXAUPRM20248E1657",
          deviceName: "NewCharger",
          activationDate: "2024-09-16 07:00:55",
          registeredAt: "2024-09-16 07:00:39",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-16 07:00:55",
          status: "activated",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 752047,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "8E1657",
        },
        {
          serialNumber: "10462D1C19F445C0",
          chargeBoxId: "CGXAUPRM20248B2EFF",
          deviceName: "NewCharger",
          activationDate: "2024-09-16 07:01:42",
          registeredAt: "2024-09-16 07:01:28",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-16 07:01:42",
          status: "activated",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 127986,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "8B2EFF",
        },
        {
          serialNumber: "B59D6B79DD5E43FB",
          chargeBoxId: "CGXAUPRM2024200DD5",
          deviceName: "NewCharger",
          activationDate: "2024-09-16 07:05:22",
          registeredAt: "2024-09-16 07:04:56",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-16 07:05:22",
          status: "activated",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 102280,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "200DD5",
        },
        {
          serialNumber: "DD46BBC3FCA244E1",
          chargeBoxId: "CGXAIPRM20248B5412",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-16 07:12:18",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "jUKO8M",
          activationExpiresAt: "2024-09-23 07:16:27",
          activationRequestedAt: "2024-09-16 07:16:27",
          deviceAdminPassCode: 572640,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AI",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "8B5412",
        },
        {
          serialNumber: "A9F787664B5547CF",
          chargeBoxId: "CGXALPRM2024782615",
          deviceName: "VoltTest",
          activationDate: null,
          registeredAt: "2024-09-16 07:17:49",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "mzadRn",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 800495,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AL",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "cc2" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "782615",
        },
        {
          serialNumber: "39A929B498E9406B",
          chargeBoxId: "CGXAIPRM2024118EB4",
          deviceName: "VoltTest",
          activationDate: null,
          registeredAt: "2024-09-16 07:19:23",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "qX5ZmO",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 942585,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "Prime",
          connectorPair: "",
          country: "AI",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "118EB4",
        },
        {
          serialNumber: "41757CB733444605",
          chargeBoxId: "CGXAWPRM2024D94AB5",
          deviceName: "NewCharger",
          activationDate: "2024-09-16 07:20:34",
          registeredAt: "2024-09-16 07:20:19",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-16 07:20:34",
          status: "activated",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 247189,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AW",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "D94AB5",
        },
        {
          serialNumber: "7EFC6429B26A4FAE",
          chargeBoxId: "CGXMYPRM20248F2349",
          deviceName: "volt05",
          activationDate: null,
          registeredAt: "2024-09-16 07:34:15",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "XMZ0L5",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 224092,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "Prime",
          connectorPair: null,
          country: "MY",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "8F2349",
        },
        {
          serialNumber: "4B621856FAC94A1D",
          chargeBoxId: "CGXMYPRM2024CAE6B0",
          deviceName: "Test device34",
          activationDate: null,
          registeredAt: "2024-09-16 07:37:10",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "Cuoe9L",
          activationExpiresAt: "2024-09-23 07:37:33",
          activationRequestedAt: "2024-09-16 07:37:33",
          deviceAdminPassCode: 255642,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "Prime",
          connectorPair: null,
          country: "MY",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "CAE6B0",
        },
        {
          serialNumber: "556D4F9347C24048",
          chargeBoxId: "CGXADPRM20248A39B1",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-16 07:41:35",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "jpx4tB",
          activationExpiresAt: "2024-09-23 07:41:46",
          activationRequestedAt: "2024-09-16 07:41:46",
          deviceAdminPassCode: 280376,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AD",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "8A39B1",
        },
        {
          serialNumber: "DEE929DD230A4B3A",
          chargeBoxId: "CGXATPRM2024C3EACA",
          deviceName: "NewCharger",
          activationDate: "2024-09-16 09:18:22",
          registeredAt: "2024-09-16 09:18:06",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-16 09:18:22",
          status: "activated",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 987085,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "Prime",
          connectorPair: null,
          country: "AT",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "C3EACA",
        },
        {
          serialNumber: "1B872C6E98634595",
          chargeBoxId: "CGXAUPRM2024F21F45",
          deviceName: "NewCharger",
          activationDate: "2024-09-16 09:36:10",
          registeredAt: "2024-09-16 09:35:53",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-16 09:36:10",
          status: "activated",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 158336,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          evseOwnerId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "F21F45",
        },
        {
          serialNumber: "9D1165C5D8744DEF",
          chargeBoxId: "CGXAUPRM202401D09E",
          deviceName: "PR",
          activationDate: "2024-09-16 09:46:59",
          registeredAt: "2024-09-16 09:46:46",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-16 09:46:59",
          status: "activated",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 774791,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "Prime",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "01D09E",
        },
        {
          serialNumber: "FC397B9E404A4E35",
          chargeBoxId: "CGXAUPRM202463B566",
          deviceName: "NewCharger",
          activationDate: "2024-09-16 10:05:26",
          registeredAt: "2024-09-16 10:04:56",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-16 10:05:26",
          status: "available",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 251296,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "Prime",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: "Available",
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "63B566",
        },
        {
          serialNumber: "3A29D67B9AF645D8",
          chargeBoxId: "CGXAUPRM2024388BC2",
          deviceName: "NewCharger",
          activationDate: "2024-09-16 11:40:39",
          registeredAt: "2024-09-16 11:40:13",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-16 11:40:39",
          status: "activated",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 582535,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "Prime",
          connectorPair: null,
          country: "AU",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "388BC2",
        },
        {
          serialNumber: "CF868B8ED7A74D22",
          chargeBoxId: "CGXINPRM202472E1ED",
          deviceName: "Test device34",
          activationDate: "2024-09-17 17:20:42",
          registeredAt: "2024-09-17 17:20:19",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-17 17:20:42",
          status: "available",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 791373,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "Prime",
          connectorPair: null,
          country: "IN",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: "Available",
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "72E1ED",
        },
        {
          serialNumber: "AE3BDD24D41E4D07",
          chargeBoxId: "CGXINPRM2024DFA411",
          deviceName: "Test device34",
          activationDate: "2024-09-18 05:15:43",
          registeredAt: "2024-09-18 05:15:17",
          lat: "19.1109087",
          lng: "73.0286094",
          validTill: "2027-09-18 05:15:43",
          status: "offline",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 856935,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "Prime",
          connectorPair: null,
          country: "IN",
          timezone: null,
          lastHeartbeat: "2024-09-24 10:24:53",
          chargingStatus: "Finishing",
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "DFA411",
        },
        {
          serialNumber: "54FBB61678F94C75",
          chargeBoxId: "CGXAWPRM20246FF79E",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-19 07:27:46",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "3X1pdJ",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 448298,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: "",
          country: "AW",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 1,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "6FF79E",
        },
        {
          serialNumber: "14E4863EC9F94E63",
          chargeBoxId: "CGXSGPRM202496F2DF",
          deviceName: "Charger 1",
          activationDate: null,
          registeredAt: "2024-09-19 12:10:29",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "bCywGv",
          activationExpiresAt: "2024-09-26 12:14:00",
          activationRequestedAt: "2024-09-19 12:14:00",
          deviceAdminPassCode: 999589,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "Prime",
          connectorPair: "",
          country: "SG",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseOwnerId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "96F2DF",
        },
        {
          serialNumber: "20C1E95F21254D95",
          chargeBoxId: "CGXSGPRM2024C2799F",
          deviceName: "Charger 2",
          activationDate: null,
          registeredAt: "2024-09-19 12:20:19",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "iLa4mI",
          activationExpiresAt: "2024-09-26 12:20:51",
          activationRequestedAt: "2024-09-19 12:20:51",
          deviceAdminPassCode: 947855,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "Prime",
          connectorPair: "",
          country: "SG",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          evseOwnerId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "C2799F",
        },
        {
          serialNumber: "E7F81206ACD7457F",
          chargeBoxId: "CGXSGPRM202480E302",
          deviceName: "Charger 3",
          activationDate: null,
          registeredAt: "2024-09-19 12:21:31",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "sFK9QJ",
          activationExpiresAt: "2024-09-26 12:23:21",
          activationRequestedAt: "2024-09-19 12:23:21",
          deviceAdminPassCode: 390776,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "Prime",
          connectorPair: "",
          country: "SG",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "cc2" },
            })
          ).id,
          evseOwnerId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "80E302",
        },
        {
          serialNumber: "5A826318CD204669",
          chargeBoxId: "CGXSGPRM202448B303",
          deviceName: "Charger 4",
          activationDate: null,
          registeredAt: "2024-09-19 12:23:49",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "pf39DE",
          activationExpiresAt: "2024-09-26 12:26:35",
          activationRequestedAt: "2024-09-19 12:26:35",
          deviceAdminPassCode: 719262,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: "",
          country: "SG",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          evseOwnerId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "48B303",
        },
        {
          serialNumber: "345E903D85B14F88",
          chargeBoxId: "CGXSGPRM202401EBFF",
          deviceName: "Charger 5",
          activationDate: null,
          registeredAt: "2024-09-19 12:27:08",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "zFjExW",
          activationExpiresAt: "2024-09-26 12:27:29",
          activationRequestedAt: "2024-09-19 12:27:29",
          deviceAdminPassCode: 919082,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: "",
          country: "SG",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          evseOwnerId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "01EBFF",
        },
        {
          serialNumber: "A1E59AE4EAF24598",
          chargeBoxId: "CGXSGPRM20242F709B",
          deviceName: "NewCharger",
          activationDate: null,
          registeredAt: "2024-09-19 13:36:34",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "ilW9Bd",
          activationExpiresAt: "2024-09-26 13:36:43",
          activationRequestedAt: "2024-09-19 13:36:43",
          deviceAdminPassCode: 139447,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "SG",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_1" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "2F709B",
        },
        {
          serialNumber: "B6752424DFFA4DE9",
          chargeBoxId: "CGXSGPRM20243700B8",
          deviceName: "NewCharger",
          activationDate: "2024-09-19 13:41:24",
          registeredAt: "2024-09-19 13:37:48",
          lat: "1.3586",
          lng: "103.9899",
          validTill: "2027-09-19 13:41:24",
          status: "available",
          activationCode: null,
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 171015,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: null,
          country: "SG",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: "Available",
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "3700B8",
        },
        {
          serialNumber: "D30F9612A2E249EC",
          chargeBoxId: "CGXSGPRM20240A86B6",
          deviceName: "NewCharger1",
          activationDate: null,
          registeredAt: "2024-09-20 10:11:15",
          lat: null,
          lng: null,
          validTill: null,
          status: "registered",
          activationCode: "ExFtbJ",
          activationExpiresAt: null,
          activationRequestedAt: null,
          deviceAdminPassCode: 933779,
          baseCost: 0.0,
          currency: "USD",
          chargerModel: "PR",
          connectorPair: "",
          country: "SG",
          timezone: null,
          lastHeartbeat: null,
          chargingStatus: null,
          isDeleted: 0,
          connectorTypeId: (
            await ChargerConnectorTypeRepository.findOne({
              where: { mappingText: "type_2" },
            })
          ).id,
          evseStationId: null,
          chargeUsageTypeId,
          updatedBy: null,
          uniqueId: "0A86B6",
        },
      ];

      await ChargerRepository.save(chargers);
      console.log("Chargers seeding done.");
    }
  } catch (error) {
    console.error("Error Seeding Chargers in database:", error);
  }
};

module.exports = { SeedChargers };
