const { LanguageRepository } = require("@shared-libs/db/mysql");

const SeedLanguage = async () => {
  try {
    // Check if there are existing records
    const lngData = await LanguageRepository.find();

    if (lngData.length === 0) {
      const langData = {
        101: {
          en: "Leakage current detected in DC circuit. Charging halted for safety. Contact support team.",
          fr: "Courant de fuite détecté dans le circuit CC. Charge interrompue pour des raisons de sécurité. Contactez l'assistance.",
          es: "Se detectó corriente de fuga en el circuito de CC. Carga detenida por seguridad. Contacte al equipo de soporte.",
          langFor: "app",
        },
        102: {
          en: "Leakage current detected in AC circuit. Charging halted for safety. Contact support team.",
          fr: "Courant de fuite détecté dans le circuit CA. Charge interrompue pour des raisons de sécurité. Contactez l'assistance.",
          es: "Se detectó corriente de fuga en el circuito de CA. Carga detenida por seguridad. Contacte al equipo de soporte.",
          langFor: "app",
        },
        103: {
          en: "Ground fault detected. Please check the earthing system or contact support team.",
          fr: "Défaut de terre détecté. Veuillez vérifier le système de mise à la terre ou contacter l'assistance.",
          es: "Se detectó una falla a tierra. Revise el sistema de puesta a tierra o contacte con el equipo de soporte.",
          langFor: "app",
        },
        107: {
          en: "The emergency switch has been triggered. Check for safety hazards or contact support team.",
          fr: "L'interrupteur d'urgence a été déclenché. Vérifier s'il y a des risques pour la sécurité ou contacter l'équipe d'assistance.",
          es: "Se ha activado el interruptor de emergencia. Verifique riesgos de seguridad o contacte al equipo de soporte.",
          langFor: "app",
        },
        109: {
          en: "Power supply lost unexpectedly. Verify power source.",
          fr: "Perte d'alimentation inattendue. Vérifiez la source d'alimentation.",
          es: "Se perdió la alimentación inesperadamente. Verifique la fuente de alimentación.",
          langFor: "app",
        },
        111: {
          en: "The charge controller is in an unknown state (State F). Restart required.",
          fr: "Le contrôleur de charge est dans un état inconnu (état F). Redémarrage requis.",
          es: "El controlador de carga se encuentra en un estado desconocido (estado F). Es necesario reiniciar.",
          langFor: "app",
        },
        116: {
          en: "System temperature is too high",
          fr: "La température du système est trop élevée",
          es: "La temperatura del sistema es demasiado alta",
          langFor: "app",
        },
        117: {
          en: "Excessive current detected.",
          fr: "Courant excessif détecté.",
          es: "Se detectó corriente excesiva.",
          langFor: "app",
        },
        118: {
          en: "METERING ERROR Voltage exceeded safe levels",
          fr: "ERREUR DE MESURE La tension a dépassé les niveaux de sécurité",
          es: "ERROR DE MEDICIÓN El voltaje excedió los niveles seguros",
          langFor: "app",
        },
        119: {
          en: "Voltage dropped below safe levels",
          fr: "La tension est tombée en dessous des niveaux de sécurité",
          es: "El voltaje cayó por debajo de los niveles seguros",
          langFor: "app",
        },
        120: {
          en: "The energy meter is unresponsive. Contact Support Team",
          fr: "Le compteur d'énergie ne répond plus. Contactez l'équipe d'assistance.",
          es: "El medidor de energía no responde. Contacte al equipo de soporte.",
          langFor: "app",
        },
        121: {
          en: "The network module is missing or not detected. Check hardware connections.",
          fr: "Le module réseau est manquant ou non détecté. Vérifiez les connexions matérielles.",
          es: "El módulo de red está ausente o no detectado. Verifique conexiones de hardware.",
          langFor: "app",
        },
        122: {
          en: "The vehicle is grounded (State E). Verify vehicle connection.",
          fr: "Le véhicule est mis à la terre (état E). Vérifiez la connexion du véhicule.",
          es: "El vehículo está conectado a tierra (estado E). Verifique la conexión del vehículo.",
          langFor: "app",
        },
        123: {
          en: "Communication failure with payment components. Contact support team.",
          fr: "Échec de communication avec les composants de paiement. Contactez l'équipe d'assistance.",
          es: "Fallo de comunicación con los componentes de pago. Contacte al equipo de soporte.",
          langFor: "app",
        },
        124: {
          en: "Internal system communication issue. Restart recommended",
          fr: "Problème de communication interne du système. Redémarrage recommandé.",
          es: "Problema de comunicación interna del sistema. Se recomienda reiniciar.",
          langFor: "app",
        },
        126: {
          en: "Unable to communicate with the backend server.",
          fr: "Impossible de communiquer avec le serveur backend.",
          es: "No se puede comunicar con el servidor backend.",
          langFor: "app",
        },
        127: {
          en: "Real-time clock (RTC) module is unresponsive",
          fr: "Le module d'horloge en temps réel (RTC) ne répond pas",
          es: "El módulo de reloj de tiempo real (RTC) no responde",
          langFor: "app",
        },
        128: {
          en: "Charge Control Board is not responding. Contact support team.",
          fr: "Le panneau de contrôle de charge ne répond pas. Contactez l'assistance.",
          es: "La placa de control de carga no responde. Contacte al equipo de soporte.",
          langFor: "app",
        },
        129: {
          en: "METERING ERROR Insufficient current detected",
          fr: "ERREUR DE MESURE Courant insuffisant détecté",
          es: "ERROR DE MEDICIÓN Corriente insuficiente detectada",
          langFor: "app",
        },
        130: {
          en: "A hard reset has been requested via OCPP. Restarting the system is required.",
          fr: "Une réinitialisation dure a été demandée via OCPP. Le redémarrage du système est nécessaire.",
          es: "Se ha solicitado un restablecimiento completo mediante OCPP. Es necesario reiniciar el sistema.",
          langFor: "app",
        },
        131: {
          en: "A soft reset has been requested via OCPP. System rebooting soon",
          fr: "Une réinitialisation douce a été demandée via OCPP. Le système va bientôt redémarrer",
          es: "Se ha solicitado un reinicio suave a través de OCPP. El sistema se reiniciará pronto.",
          langFor: "app",
        },
        132: {
          en: "Internet connection is unavailable. Verify network.",
          fr: "Connexion Internet indisponible. Vérifiez le réseau.",
          es: "La conexión a Internet no está disponible. Por favor verifique la red.",
          langFor: "app",
        },
        133: {
          en: "Charger Not configured, Contact Support Team.",
          fr: "Chargeur non configuré, contactez l'équipe d'assistance.",
          es: "Cargador no configurado, contacte al equipo de soporte.",
          langFor: "app",
        },
        "If you need assistance, our support team is here to help!": {
          en: "If you need assistance, our support team is here to help!",
          fr: "Si vous avez besoin d’aide, notre équipe d’assistance est là pour vous aider!",
          es: "Si necesita ayuda, ¡nuestro equipo de soporte está aquí para ayudarle!",
          langFor: "app",
        },
        Next: {
          en: "Next",
          fr: "Suivant",
          es: "Siguiente",
          langFor: "app",
        },
        "User not found. Please check your email.": {
          en: "User not found. Please check your email.",
          fr: "Utilisateur non trouvé. Veuillez vérifier votre e-mail.",
          es: "Usuario no encontrado. Por favor, verifique su correo electrónico.",
          langFor: "app",
        },
        "Payment Gateway": {
          en: "Payment Gateway",
          fr: "Passerelle de paiement",
          es: "Pasarela de pago",
          langFor: "app",
        },
        "Enter your registered email ID to verify your account and proceed.": {
          en: "Enter your registered email ID to verify your account and proceed.",
          fr: "Saisissez l'adresse électronique que vous avez enregistrée pour vérifier votre compte et continuez.",
          es: "Por favor, introduzca su dirección de correo electrónico registrada para verificar su cuenta y continuar.",
          langFor: "app",
        },
        "Energy added": {
          en: "Energy added",
          fr: "Énergie ajoutée",
          es: "Energía agregada",
          langFor: "app",
        },
        "Serial no.": {
          en: "Serial no.",
          fr: "Numéro de série",
          es: "Número de serie",
          langFor: "app",
        },
        "Payment Successful": {
          en: "Payment Successful",
          fr: "Paiement réussi",
          es: "Pago exitoso",
          langFor: "app",
        },
        "Please wait while your payment is being verified. This may take a few moments.":
          {
            en: "Please wait while your payment is being verified. This may take a few moments.",
            fr: "Veuillez patienter pendant la vérification de votre paiement. Cela peut prendre quelques instants.",
            es: "Por favor, espere mientras se verifica su pago. Esto puede tomar unos minutos.",
            langFor: "app",
          },
        "The cost is calculated based on the energy consumed (kWh) and the charging duration. The display shows the ongoing cost in real time, and the final amount is displayed at the end of the session. For detailed transaction history, scan QR to download the receipt.":
          {
            en: "The cost is calculated based on the energy consumed (kWh) and the charging duration. The display shows the ongoing cost in real time, and the final amount is displayed at the end of the session. For detailed transaction history, scan QR to download the receipt.",
            fr: "Le coût est calculé en fonction de l'énergie consommée (kWh) et de la durée de la charge. L'écran affiche le coût en cours en temps réel et le montant final est affiché à la fin de la session. Pour un historique détaillé de la transaction, scannez le QR pour télécharger le reçu.",
            es: "El costo se calcula según la energía consumida (kWh) y la duración de la carga. La pantalla muestra el costo en tiempo real y el monto final se muestra al terminar la sesión. Para el historial detallado de transacciones, escanee el código QR para descargar el recibo.",
            langFor: "app",
          },
        "Open Volt Check App": {
          en: "Open Volt Check App",
          fr: "Ouvrir l'application Volt Check",
          es: "Abra la aplicación Volt Check",
          langFor: "app",
        },
        Settings: {
          en: "Settings",
          fr: "Paramètres",
          es: "Ajustes",
          langFor: "app",
        },
        "Pair New Device": {
          en: "Pair New Device",
          fr: "Associer un nouvel appareil",
          es: "Empareje nuevo dispositivo",
          langFor: "app",
        },
        "Wi-fi not connected": {
          en: "Wi-fi not connected",
          fr: "Wi-Fi non connecté",
          es: "Wi-fi no conectado",
          langFor: "app",
        },
        "Your feedback helps us improve and deliver a better experience!": {
          en: "Your feedback helps us improve and deliver a better experience!",
          fr: "Vos commentaires nous aident à nous améliorer et à vous offrir une meilleure expérience!",
          es: "¡Sus comentarios nos ayudan a mejorar y ofrecer una mejor experiencia!",
          langFor: "app",
        },
        "Switching Application...": {
          en: "Switching Application...",
          fr: "Changement d'application...",
          es: "Cambiando de aplicación...",
          langFor: "app",
        },
        "Connection strength": {
          en: "Connection strength",
          fr: "Puissance du connexion",
          es: "Fuerza de la conexión",
          langFor: "app",
        },
        "What payment methods are supported?": {
          en: "What payment methods are supported?",
          fr: "Quels sont les modes de paiement acceptés?",
          es: "¿Qué métodos de pago se admiten?",
          langFor: "app",
        },
        "Apply Changes": {
          en: "Apply Changes",
          fr: "Appliquer les modifications",
          es: "Aplicar cambios",
          langFor: "app",
        },
        "Wi-Fi IP Address": {
          en: "Wi-Fi IP Address",
          fr: "Adresse IP Wi-Fi",
          es: "Dirección IP de Wi-Fi",
          langFor: "app",
        },
        "Select Language": {
          en: "Select Language",
          fr: "Sélectionnez la langue",
          es: "Seleccionar idioma",
          langFor: "app",
        },
        "Tap anywhere to start": {
          en: "Tap anywhere to start",
          fr: "Appuyez n'importe où pour commencer",
          es: "Toca cualquier lugar para comenzar",
          langFor: "app",
        },
        "Remove the Plug gently from the Socket": {
          en: "Remove the Plug gently from the Socket",
          fr: "Retirer doucement la fiche de la prise",
          es: "Retire el enchufe con cuidado de la toma de corriente.",
          langFor: "app",
        },
        Time: {
          en: "Time",
          fr: "Heure",
          es: "Tiempo",
          langFor: "app",
        },
        "Charging.": {
          en: "Charging.",
          fr: "Chargement..",
          es: "Cargando.",
          langFor: "app",
        },
        Language: {
          en: "Language",
          fr: "Langue",
          es: "Idioma",
          langFor: "app",
        },
        "Please contact support or check system settings.": {
          en: "Please contact support or check system settings.",
          fr: "Veuillez contacter le support ou vérifier les paramètres système.",
          es: "Por favor contacte al soporte o revise la configuración del sistema.",
          langFor: "app",
        },
        Date: {
          en: "Date",
          fr: "Date",
          es: "Fecha",
          langFor: "app",
        },
        "STEP 1": {
          en: "STEP 1",
          fr: "1ere étape",
          es: "PASO 1",
          langFor: "app",
        },
        "Leave your feedback here...": {
          en: "Leave your feedback here...",
          fr: "Laissez vos commentaires ici...",
          es: "Deje su opinión aquí...",
          langFor: "app",
        },
        "How was your charging experience?": {
          en: "How was your charging experience?",
          fr: "Comment s'est déroulée votre expérience de recharge?",
          es: "¿Cómo fue su experiencia de carga?",
          langFor: "app",
        },
        "Contact Us": {
          en: "Contact Us",
          fr: "Contactez-nous",
          es: "Contáctanos",
          langFor: "app",
        },
        "Very Good": {
          en: "Very Good",
          fr: "Très bien",
          es: "Muy buena",
          langFor: "app",
        },
        "What should I do if charging doesn’t start?": {
          en: "What should I do if charging doesn’t start?",
          fr: "Que dois-je faire si la charge ne démarre pas?",
          es: "¿Qué debo hacer si la carga no comienza?",
          langFor: "app",
        },
        "Still having issues?": {
          en: "Still having issues?",
          fr: "Toujours des problèmes?",
          es: "¿Sigue teniendo problemas?",
          langFor: "app",
        },
        "How do I stop a charging session?": {
          en: "How do I stop a charging session?",
          fr: "Comment arrêter une session de charge?",
          es: "¿Cómo detengo una sesión de carga?",
          langFor: "app",
        },
        "Pair new device": {
          en: "Pair new device",
          fr: "Associer un nouvel appareil",
          es: "Emparejar nuevo dispositivo",
          langFor: "app",
        },
        "Open Activator App": {
          en: "Open Activator App",
          fr: "Ouvrir l'application Activator",
          es: "Abrir aplicación activadora",
          langFor: "app",
        },
        GENERAL: {
          en: "GENERAL",
          fr: "GÉNÉRAL",
          es: "GENERAL",
          langFor: "app",
        },
        "Payment Timeout": {
          en: "Payment Timeout",
          fr: "Délai de paiement dépassé",
          es: "Tiempo de espera de pago agotado",
          langFor: "app",
        },
        "Retry Payment": {
          en: "Retry Payment",
          fr: "Réessayer le paiement",
          es: "Reintentar pago",
          langFor: "app",
        },
        "Note: Charging will continue until you make a payment to stop the session.":
          {
            en: "Note: Charging will continue until you make a payment to stop the session.",
            fr: "Remarque : la facturation continuera jusqu'à ce que vous effectuiez un paiement pour arrêter la session.",
            es: "Nota: La carga continuará hasta que realice un pago para detener la sesión.",
            langFor: "app",
          },
        Cancel: {
          en: "Cancel",
          fr: "Annuler",
          es: "Cancelar",
          langFor: "app",
        },
        "Please wait while the application gets switched": {
          en: "Please wait while the application gets switched",
          fr: "Veuillez patienter pendant le changement d'application",
          es: "Por favor espere mientras se cambia la aplicación",
          langFor: "app",
        },
        "No connection": {
          en: "No connection",
          fr: "Aucune connexion",
          es: "Sin conexión",
          langFor: "app",
        },
        "Trustack Version": {
          en: "Trustack Version",
          fr: "Version Trustack",
          es: "Versión de confianza",
          langFor: "app",
        },
        "Preparing to lock the plug and start charging...": {
          en: "Preparing to lock the plug and start charging...",
          fr: "Se préparer à verrouiller la prise et à commencer la charge...",
          es: "Preparando para bloquear el enchufe y comenzar a cargar...",
          langFor: "app",
        },
        Submit: {
          en: "Submit",
          fr: "Soumettre",
          es: "Enviar",
          langFor: "app",
        },
        "Client ID": {
          en: "Client ID",
          fr: "Identifiant client",
          es: "ID del cliente",
          langFor: "app",
        },
        "Change Default Language": {
          en: "Change Default Language",
          fr: "Changer la langue par défaut",
          es: "Cambiar idioma predeterminado",
          langFor: "app",
        },
        "Wi-Fi & Ethernet": {
          en: "Wi-Fi & Ethernet",
          fr: "Wi-Fi et Ethernet",
          es: "Wi-Fi y Ethernet",
          langFor: "app",
        },
        "Get Started": {
          en: "Get Started",
          fr: "Commencer",
          es: "Comenzar",
          langFor: "app",
        },
        "Didn’t receive a code?": {
          en: "Didn’t receive a code?",
          fr: "Vous n’avez pas reçu de code?",
          es: "¿No recibiste un código?",
          langFor: "app",
        },
        Skip: {
          en: "Skip",
          fr: "Ignorer",
          es: "Omitir",
          langFor: "app",
        },
        "Retry Authorization": {
          en: "Retry Authorization",
          fr: "Réessayer l'autorisation",
          es: "Reintente autorización",
          langFor: "app",
        },
        "Card Authorized": {
          en: "Card Authorized",
          fr: "Carte autorisée",
          es: "Tarjeta autorizada",
          langFor: "app",
        },
        On: {
          en: "On",
          fr: "Activé",
          es: "Encendido",
          langFor: "app",
        },
        "Processing Payment": {
          en: "Processing Payment",
          fr: "Traitement du paiement",
          es: "Procesando pago",
          langFor: "app",
        },
        Discount: {
          en: "Discount",
          fr: "Rabais",
          es: "Descuento",
          langFor: "app",
        },
        "UI Version": {
          en: "UI Version",
          fr: "Version de l'interface utilisateur",
          es: "Versión de interfaz de usuario",
          langFor: "app",
        },
        "Charging will continue until payment is made to stop it.": {
          en: "Charging will continue until payment is made to stop it.",
          fr: "La facturation se poursuivra jusqu'à ce qu'un paiement soit effectué pour l'arrêter.",
          es: "El cobro continuará hasta que se realice el pago para detenerlo.",
          langFor: "app",
        },
        "Note: Please use the same card for both authorization and stopping the charge.":
          {
            en: "Note: Please use the same card for both authorization and stopping the charge.",
            fr: "Remarque : Veuillez utiliser la même carte pour l'autorisation et l'arrêt du débit.",
            es: "Nota: Por favor use la misma tarjeta para autorizar y detener la carga.",
            langFor: "app",
          },
        Penalty: {
          en: "Penalty",
          fr: "Pénalité",
          es: "Penalización",
          langFor: "app",
        },
        "Enter Registered Email": {
          en: "Enter Registered Email",
          fr: "Entrer l'adresse électronique enregistrée",
          es: "Ingrese el correo electrónico registrado",
          langFor: "app",
        },
        Connection: {
          en: "Connection",
          fr: "Connexion",
          es: "Conexión",
          langFor: "app",
        },
        "Ensure your card or phone is placed  correctly on the reader.": {
          en: "Ensure your card or phone is placed  correctly on the reader.",
          fr: "Assurez-vous que votre carte ou votre téléphone est placé correctement sur le lecteur.",
          es: "Asegúrese de que su tarjeta o teléfono esté colocado correctamente en el lector.",
          langFor: "app",
        },
        "Please enter the 6-digit code sent to your email:": {
          en: "Please enter the 6-digit code sent to your email:",
          fr: "Veuillez saisir le code à 6 chiffres envoyé à votre adresse e-mail:",
          es: "Por favor ingrese el código de 6 dígitos enviado a su correo electrónico:",
          langFor: "app",
        },
        Subtotal: {
          en: "Subtotal",
          fr: "Sous-total",
          es: "Total parcial",
          langFor: "app",
        },
        "Software version": {
          en: "Software version",
          fr: "Version du logiciel",
          es: "Versión de software",
          langFor: "app",
        },
        "Time zone": {
          en: "Time zone",
          fr: "Fuseau horaire",
          es: "Zona horaria",
          langFor: "app",
        },
        "Request again in": {
          en: "Request again in",
          fr: "Demander à nouveau dans",
          es: "Solicite de nuevo en",
          langFor: "app",
        },
        "Contact Support": {
          en: "Contact Support",
          fr: "Contacter le support",
          es: "Contacte a soporte técnico",
          langFor: "app",
        },
        Ethernet: {
          en: "Ethernet",
          fr: "Ethernet",
          es: "Ethernet",
          langFor: "app",
        },
        "Connected to": {
          en: "Connected to",
          fr: "Connecté à",
          es: "Conectado a",
          langFor: "app",
        },
        "Nexpay Version": {
          en: "Nexpay Version",
          fr: "Version Nexpay",
          es: "Versión Nexpay",
          langFor: "app",
        },
        "4G-LTE MAC Address": {
          en: "4G-LTE MAC Address",
          fr: "Adresse MAC 4G-LTE",
          es: "Dirección MAC 4G-LTE",
          langFor: "app",
        },
        "Place the Plug gently on the Socket": {
          en: "Place the Plug gently on the Socket",
          fr: "Placez délicatement la fiche sur la prise",
          es: "Coloque el enchufe con cuidado en la toma",
          langFor: "app",
        },
        "Set time zone automatically": {
          en: "Set time zone automatically",
          fr: "Définir automatiquement le fuseau horaire",
          es: "Establecer zona horaria automáticamente",
          langFor: "app",
        },
        "Loved it!": {
          en: "Loved it!",
          fr: "J'ai adoré!",
          es: "¡Me encantó!",
          langFor: "app",
        },
        Cost: {
          en: "Cost",
          fr: "Coût",
          es: "Costo",
          langFor: "app",
        },
        WiFi: {
          en: "WiFi",
          fr: "Wi-Fi",
          es: "Wi-Fi",
          langFor: "app",
        },
        "If charging doesn’t initiate, check the screen for error messages. Ensure the charging gun is properly connected and try authorizing your card again. If the issue persists, restart the session or contact support for assistance.":
          {
            en: "If charging doesn’t initiate, check the screen for error messages. Ensure the charging gun is properly connected and try authorizing your card again. If the issue persists, restart the session or contact support for assistance.",
            fr: " Si la charge ne démarre pas, vérifiez les messages d’erreur à l’écran. Assurez-vous que la prise est correctement connectée et réessayez d’autoriser votre carte. Si le problème persiste, redémarrez la session ou contactez le support.",
            es: "Si la carga no se inicia, revise la pantalla para ver si hay mensajes de error. Asegúrese de que la pistola de carga esté correctamente conectada e intente autorizar la tarjeta de nuevo. Si el problema persiste, reinicie la sesión o contacte con el servicio de asistencia.",
            langFor: "app",
          },
        "Device BT Address": {
          en: "Device BT Address",
          fr: "Adresse BT de l'appareil",
          es: "Dirección BT del dispositivo",
          langFor: "app",
        },
        "4G-LTE IP Address": {
          en: "4G-LTE IP Address",
          fr: "Adresse IP 4G-LTE",
          es: "Dirección IP 4G-LTE",
          langFor: "app",
        },
        "WELCOME TO": {
          en: "WELCOME TO",
          fr: "BIENVENUE À",
          es: "BIENVENIDO A",
          langFor: "app",
        },
        "For urgent issues, please call our helpline. Our support team is available 24/7 to assist you.":
          {
            en: "For urgent issues, please call our helpline. Our support team is available 24/7 to assist you.",
            fr: "Pour les problèmes urgents, veuillez appeler notre ligne d’assistance. Notre équipe est disponible 24h/24 et 7j/7 pour vous aider.",
            es: "Para cuestiones urgentes, llame a nuestro teléfono de asistencia: ¡Nuestro equipo de asistencia está disponible las 24 horas al día, los 7 días a la semana!",
            langFor: "app",
          },
        "Verify & Login": {
          en: "Verify & Login",
          fr: "Vérifier et se connecter",
          es: "Verificar e iniciar sesión",
          langFor: "app",
        },
        "Set date & time automatically": {
          en: "Set date & time automatically",
          fr: "Régler la date et l'heure automatiquement",
          es: "Establecer fecha y hora automáticamente",
          langFor: "app",
        },
        "This station is inactive due to": {
          en: "This station is inactive due to",
          fr: "Cette station est inactive en raison de",
          es: "Esta estación está inactiva debido a",
          langFor: "app",
        },
        "Ethernet IP Address": {
          en: "Ethernet IP Address",
          fr: "Adresse IP Ethernet",
          es: "Dirección IP Ethernet",
          langFor: "app",
        },
        "Yes, Stop Charging": {
          en: "Yes, Stop Charging",
          fr: "Oui, arrêter la charge",
          es: "Sí, detener carga",
          langFor: "app",
        },
        "Please connect to a Wi-Fi network to proceed with the charging process.":
          {
            en: "Please connect to a Wi-Fi network to proceed with the charging process.",
            fr: "Veuillez vous connecter à un réseau Wi-Fi pour procéder à la recharge",
            es: "Por favor, conectese a una red Wi-Fi para continuar con el proceso de carga.",
            langFor: "app",
          },
        Active: {
          en: "Active",
          fr: "Actif",
          es: "Activo",
          langFor: "app",
        },
        "Set Date": {
          en: "Set Date",
          fr: "Définir la date",
          es: "Establecer fecha",
          langFor: "app",
        },
        Tax: {
          en: "Tax",
          fr: "Taxe",
          es: "Impuesto",
          langFor: "app",
        },
        "Rate your experience": {
          en: "Rate your experience",
          fr: "Évaluez votre expérience",
          es: "Valore su experiencia",
          langFor: "app",
        },
        "Output rate": {
          en: "Output rate",
          fr: "Taux de sortie",
          es: "Velocidad de salida",
          langFor: "app",
        },
        "Authorization Timeout": {
          en: "Authorization Timeout",
          fr: "Délai d'attente pour l'autorisation",
          es: "Tiempo límite de autorización",
          langFor: "app",
        },
        Configurations: {
          en: "Configurations",
          fr: "Configurations",
          es: "Configuraciones",
          langFor: "app",
        },
        "DA Version": {
          en: "DA Version",
          fr: "Version DA",
          es: "Versión DA",
          langFor: "app",
        },
        "To stop charging, tap the same card used to start the session on the charger screen. The session will end, and the display will show a Charging Complete message. You can then safely unplug the charging gun from your vehicle.":
          {
            en: "To stop charging, tap the same card used to start the session on the charger screen. The session will end, and the display will show a Charging Complete message. You can then safely unplug the charging gun from your vehicle.",
            fr: "Pour arrêter la charge, présentez la même carte utilisée au début sur l’écran du chargeur. La session se terminera et un message « Charge terminée » s’affichera. Vous pourrez alors débrancher la prise en toute sécurité.",
            es: "Para detener la carga, toque en la pantalla del cargador con la misma tarjeta que usó para iniciar la sesión. La sesión finalizará y la pantalla mostrará el mensaje Carga completa. A continuación, podrá desconectar la pistola de carga del vehículo de forma segura.",
            langFor: "app",
          },
        "Connecting...": {
          en: "Connecting...",
          fr: "Connexion en cours...",
          es: "Conectando...",
          langFor: "app",
        },
        "Chargebox ID": {
          en: "Chargebox ID",
          fr: "ID de la borne",
          es: "ID de la caja de carga",
          langFor: "app",
        },
        "hold will be placed to authorise charging. It’s not a charge and will be adjusted post-session.":
          {
            en: "hold will be placed to authorise charging. It’s not a charge and will be adjusted post-session.",
            fr: "une mise en attente sera effectuée pour autoriser la facturation. Il ne s'agit pas d'une charge et elle sera ajustée après la session.",
            es: "Se realizará una retención para autorizar el cobro. El cobro no se realizará y se ajustará después de la sesión.",
            langFor: "app",
          },
        "Charging Halted!.": {
          en: "Charging Halted!.",
          fr: "Chargement arrêté!",
          es: "¡Carga detenida!.",
          langFor: "app",
        },
        "Access Point Name": {
          en: "Access Point Name",
          fr: "Nom du point d'accès",
          es: "Nombre del punto de acceso",
          langFor: "app",
        },
        "No response detected within the time limit. Please tap your card again to proceed.":
          {
            en: "No response detected within the time limit. Please tap your card again to proceed.",
            fr: "Aucune réponse détectée dans le délai imparti. Veuillez taper à nouveau sur votre carte pour continuer.",
            es: "No se detectó respuesta dentro del tiempo límite. Por favor, toque con su tarjeta nuevamente para continuar.",
            langFor: "app",
          },
        "(pre-tax)": {
          en: "(pre-tax)",
          fr: "(avant impôt)",
          es: "(antes de impuestos)",
          langFor: "app",
        },
        "STEP 2": {
          en: "STEP 2",
          fr: "2e étape",
          es: "PASO 2",
          langFor: "app",
        },
        "Invalid code! Please check the code & retry": {
          en: "Invalid code! Please check the code & retry",
          fr: "Code invalide! Veuillez vérifier le code et réessayer.",
          es: "¡Código inválido! Por favor, verifique el código y vuelva a intentarlo.",
          langFor: "app",
        },
        "Release Type": {
          en: "Release Type",
          fr: "Type de version",
          es: "Tipo de lanzamiento",
          langFor: "app",
        },
        "Waiting for Vehicle Response": {
          en: "Waiting for Vehicle Response",
          fr: "En attente de la réponse du véhicule",
          es: "Esperando la respuesta del vehículo",
          langFor: "app",
        },
        "Enter CSMS URL": {
          en: "Enter CSMS URL",
          fr: "Entrez l'URL CSMS",
          es: "Ingrese la URL de CSMS",
          langFor: "app",
        },
        "How is the charging cost calculated?": {
          en: "How is the charging cost calculated?",
          fr: "Comment le coût de la charge est-il calculé?",
          es: "¿Cómo se calcula el coste de carga?",
          langFor: "app",
        },
        NETWORK: {
          en: "NETWORK",
          fr: "RÉSEAU",
          es: "RED",
          langFor: "app",
        },
        "Save Changes": {
          en: "Save Changes",
          fr: "Enregistrer les modifications",
          es: "Guardar cambios",
          langFor: "app",
        },
        "Wi-Fi MAC Address": {
          en: "Wi-Fi MAC Address",
          fr: "Adresse MAC Wi-Fi",
          es: "Dirección MAC de Wi-Fi",
          langFor: "app",
        },
        "Report Problem": {
          en: "Report Problem",
          fr: "Signaler un problème",
          es: "Reportar problema",
          langFor: "app",
        },
        "Select Time Zone": {
          en: "Select Time Zone",
          fr: "Sélectionner le fuseau horaire",
          es: "Seleccionar zona horaria",
          langFor: "app",
        },
        "About Charger": {
          en: "About Charger",
          fr: "À propos du chargeur",
          es: "Acerca del cargador",
          langFor: "app",
        },
        Off: {
          en: "Off",
          fr: "Désactivé",
          es: "Apagado",
          langFor: "app",
        },
        Continue: {
          en: "Continue",
          fr: "Continuer",
          es: "Continuar",
          langFor: "app",
        },
        "Stop Charging?": {
          en: "Stop Charging",
          fr: "Arrêter de charger?",
          es: "¿Dejar de cargar?",
          langFor: "app",
        },
        Good: {
          en: "Good",
          fr: "Bien",
          es: "Buena",
          langFor: "app",
        },
        Enabled: {
          en: "Enabled",
          fr: "Activé",
          es: "Activado",
          langFor: "app",
        },
        "Peak Hour Charges": {
          en: "Peak Hour Charges",
          fr: "Frais pour les heures de pointe",
          es: "Tarifa durante horas de alta demanda",
          langFor: "app",
        },
        "Please wait while your vehicle communicates with the charger. This may take a few moments.":
          {
            en: "Please wait while your vehicle communicates with the charger. This may take a few moments.",
            fr: "Veuillez patienter pendant que votre véhicule communique avec le chargeur. Cela peut prendre quelques instants.",
            es: "Por favor, espere mientras su vehículo se comunica con el cargador. Esto puede tomar unos minutos.",
            langFor: "app",
          },
        "UF2 Version": {
          en: "UF2 Version",
          fr: "Version UF2",
          es: "Versión UF2",
          langFor: "app",
        },
        "View Cost Breakdown": {
          en: "View Cost Breakdown",
          fr: "Voir la répartition des coûts",
          es: "Ver desglose de costos",
          langFor: "app",
        },
        "Parking Fee": {
          en: "Parking Fee",
          fr: "Frais de stationnement",
          es: "Tarifa de estacionamiento",
          langFor: "app",
        },
        "How do I start a charging session?": {
          en: "How do I start a charging session?",
          fr: "Comment démarrer une session de charge?",
          es: "¿Cómo inicio una sesión de carga?",
          langFor: "app",
        },
        "Set Time": {
          en: "Set Time",
          fr: "Définir l'heure",
          es: "Establecer hora",
          langFor: "app",
        },
        "Not Connected": {
          en: "Not Connected",
          fr: "Non connecté",
          es: "No conectado",
          langFor: "app",
        },
        "FREQUENTLY ASKED QUESTIONS": {
          en: "FREQUENTLY ASKED QUESTIONS",
          fr: "QUESTIONS FRÉQUEMMENT POSÉES",
          es: "PREGUNTAS FRECUENTES",
          langFor: "app",
        },
        Connect: {
          en: "Connect",
          fr: "Connecter",
          es: "Conectar",
          langFor: "app",
        },
        "Note: Only registered users and CPOs will receive the verification code.":
          {
            en: "Note: Only registered users and CPOs will receive the verification code.",
            fr: "Remarque : seuls les utilisateurs enregistrés et les CPO recevront le code de vérification.",
            es: "Nota: Solo los usuarios registrados y los CPO recibirán el código de verificación.",
            langFor: "app",
          },
        "Resend code": {
          en: "Resend code",
          fr: "Renvoyer le code",
          es: "Reenviar código",
          langFor: "app",
        },
        Excellent: {
          en: "Excellent",
          fr: "Excellent",
          es: "Excelente",
          langFor: "app",
        },
        Connected: {
          en: "Connected",
          fr: "Connecté",
          es: "Conectado",
          langFor: "app",
        },
        "Charging isn’t complete. Stopping now may leave your battery undercharged. Still want to end?":
          {
            en: "Charging isn’t complete. Stopping now may leave your battery undercharged. Still want to end?",
            fr: "La charge n'est pas terminée. Si vous arrêtez maintenant, votre batterie risque de ne pas être suffisamment chargée. Vous souhaitez toujours terminer?",
            es: "La carga aún no está completada. Si se detiene ahora, la batería podría quedarse sin carga. ¿Aun así desea detenerla?",
            langFor: "app",
          },
        "To start charging, connect the charging gun to your vehicle first, then tap your card on the reader to authorize it. Wait for the charger to establish a connection. Once the session begins, you can monitor the progress on the display.":
          {
            en: "To start charging, connect the charging gun to your vehicle first, then tap your card on the reader to authorize it. Wait for the charger to establish a connection. Once the session begins, you can monitor the progress on the display.",
            fr: "Pour commencer la charge, connectez d'abord le chargeur à votre véhicule, puis présentez votre carte au lecteur pour l'autoriser. Attendez que le chargeur établisse la connexion. Une fois la session lancée, vous pourrez suivre sa progression sur l'écran.",
            es: "Para iniciar la carga, primero conecte la pistola de carga a su vehículo y luego acerque su tarjeta al lector para autorizarla. Espere a que el cargador se conecte. Una vez iniciada la sesión, podrá monitorear el progreso en la pantalla.",
            langFor: "app",
          },
        "4G LTE": {
          en: "4G LTE",
          fr: "4G LTE",
          es: "4G LTE",
          langFor: "app",
        },
        "Error Code": {
          en: "Error Code",
          fr: "Code d'erreur",
          es: "Código de error",
          langFor: "app",
        },
        "Model name": {
          en: "Model name",
          fr: "Nom du modèle",
          es: "Nombre del modelo",
          langFor: "app",
        },
        "Network strength": {
          en: "Network strength",
          fr: "Puissance du réseau",
          es: "Fortaleza de la red",
          langFor: "app",
        },
        "Note: A": {
          en: "Note: A",
          fr: "Remarque : un",
          es: "Nota: Una",
          langFor: "app",
        },
        "Session energy": {
          en: "Session energy",
          fr: "Énergie de la session",
          es: "Energía de sesión",
          langFor: "app",
        },
        "Volt check app is the troubleshooting app": {
          en: "Volt check app is the troubleshooting app",
          fr: "L'application Volt Check est l'application de dépannage",
          es: "La aplicación Volt Check es para resolución de problemas",
          langFor: "app",
        },
        "Cost Breakdown": {
          en: "Cost Breakdown",
          fr: "Répartition des coûts",
          es: "Desglose de costos",
          langFor: "app",
        },
        "Having issues?": {
          en: "Having issues?",
          fr: "Vous avez des problèmes?",
          es: "¿Tienes problemas?",
          langFor: "app",
        },
        Disabled: {
          en: "Disabled",
          fr: "Désactivé",
          es: "Desactivado",
          langFor: "app",
        },
        "Client ID:": {
          en: "Client ID:",
          fr: "ID du client:",
          es: "ID del cliente:",
          langFor: "app",
        },
        "Select Language To Begin": {
          en: "Select Language To Begin",
          fr: "Sélectionnez la langue pour commencer",
          es: "Seleccione el idioma para comenzar",
          langFor: "app",
        },
        "Dark Theme": {
          en: "Dark Theme",
          fr: "Thème sombre",
          es: "Tema oscuro",
          langFor: "app",
        },
        "Help & Support": {
          en: "Help & Support",
          fr: "Aide & Assistance",
          es: "Ayuda y soporte",
          langFor: "app",
        },
        Phone: {
          en: "Phone",
          fr: "Téléphone",
          es: "Teléfono",
          langFor: "app",
        },
        "Available Networks": {
          en: "Available Networks",
          fr: "Réseaux disponibles",
          es: "Redes disponibles",
          langFor: "app",
        },
        "Stop Charging": {
          en: "Stop Charging",
          fr: "Arrêt du chargement",
          es: "Dejar de cargar",
          langFor: "app",
        },
        Email: {
          en: "Email",
          fr: "E-mail",
          es: "Correo electrónico",
          langFor: "app",
        },
        "Tap Your Card to Begin Charging!": {
          en: "Tap Your Card to Begin Charging!",
          fr: "Tapper votre carte pour commencer la charge!",
          es: "¡Toque con su tarjeta para empezar a cargar!",
          langFor: "app",
        },
        "Incorrect Password!": {
          en: "Incorrect Password!",
          fr: "Mot de passe incorrect !",
          es: "¡Contraseña incorrecta!",
          langFor: "app",
        },
        "Energy dispense rate": {
          en: "Energy dispense rate",
          fr: "Taux de distribution de l'énergie",
          es: "Tasa de entrega de energía",
          langFor: "app",
        },
        "Ethernet MAC Address": {
          en: "Ethernet MAC Address",
          fr: "Adresse MAC Ethernet",
          es: "Dirección MAC de Ethernet",
          langFor: "app",
        },
        "Date & Time": {
          en: "Date & Time",
          fr: "Date et heure",
          es: "Fecha y hora",
          langFor: "app",
        },
        "Thanks again for choosing Chargnex. Scan the QR code  to download your receipt":
          {
            en: "Thanks again for choosing Chargnex. Scan the QR code  to download your receipt",
            fr: " Merci encore d’avoir choisi Chargnex. Scannez le code QR pour télécharger votre reçu",
            es: "Gracias de nuevo por elegir Chargnex. Escanee el código QR para descargar su recibo",
            langFor: "app",
          },
        Bluetooth: {
          en: "Bluetooth",
          fr: "Bluetooth",
          es: "Bluetooth",
          langFor: "app",
        },
        "Connector type": {
          en: "Connector type",
          fr: "Type de connecteur",
          es: "Tipo de conector",
          langFor: "app",
        },
        Poor: {
          en: "Poor",
          fr: "Mauvais",
          es: "Pobre",
          langFor: "app",
        },
        "Off Peak Hour Charges": {
          en: "Off Peak Hour Charges",
          fr: "Frais d'heures creuses",
          es: "Tarifa durante horas de baja demanda",
          langFor: "app",
        },
        "OS Version": {
          en: "OS Version",
          fr: " Version de l’OS",
          es: "Versión del sistema operativo",
          langFor: "app",
        },
        Inactive: {
          en: "Inactive",
          fr: "Inactif",
          es: "Inactivo",
          langFor: "app",
        },
        "Go to Settings": {
          en: "Go to Settings",
          fr: "Accéder aux paramètres",
          es: "Ir a configuración",
          langFor: "app",
        },
        "Select OCPP Version": {
          en: "Select OCPP Version",
          fr: "Sélectionnez la version OCPP",
          es: "Seleccione la versión de OCPP",
          langFor: "app",
        },
        "Payment Failed!": {
          en: "Payment Failed!",
          fr: "Échec du paiement!",
          es: "¡Pago fallido!",
          langFor: "app",
        },
        "No, Continue Charging": {
          en: "No, Continue Charging",
          fr: "Non, continuer la charge",
          es: "No, continuar cargando",
          langFor: "app",
        },
        "Total cost": {
          en: "Total cost",
          fr: "Coût total",
          es: "Costo total",
          langFor: "app",
        },
        Theme: {
          en: "Theme",
          fr: "Thème",
          es: "Tema",
          langFor: "app",
        },
        "Authorization Failed": {
          en: "Authorization Failed",
          fr: "Échec de l'autorisation",
          es: "Autorización fallida",
          langFor: "app",
        },
        "Enter Passcode": {
          en: "Enter Passcode",
          fr: "Entrez le code d'accès",
          es: "Ingrese la contraseña",
          langFor: "app",
        },
        "Tap Your Card to Stop Charging!": {
          en: "Tap Your Card to Stop Charging!",
          fr: "Taper votre carte pour arrêter la charge!",
          es: "Toque con su tarjeta para detener el cobro",
          langFor: "app",
        },
        "See all available networks": {
          en: "See all available networks",
          fr: "Voir tous les réseaux disponibles",
          es: "Ver todas las redes disponibles",
          langFor: "app",
        },
        "Authorization in Progress": {
          en: "Authorization in Progress",
          fr: "Autorisation en cours",
          es: "Autorización en curso",
          langFor: "app",
        },
        "Tell us what could be better?": {
          en: "Tell us what could be better?",
          fr: "Dites-nous ce qui pourrait être amélioré?",
          es: "¿Cuéntanos qué podría ser mejor?",
          langFor: "app",
        },
        "Thanks for Feedback!": {
          en: "Thanks for Feedback!",
          fr: "Merci pour vos commentaires!",
          es: "¡Gracias por sus comentarios!",
          langFor: "app",
        },
        "Please wait while your card is being verified. This may take a few moments.":
          {
            en: "Please wait while your card is being verified. This may take a few moments.",
            fr: "Veuillez patienter pendant la vérification de votre carte. Cela peut prendre quelques instants",
            es: "Por favor, espere mientras se verifica tu tarjeta. Esto puede tomar unos minutos.",
            langFor: "app",
          },
        "Connect the Plug to Start Charging": {
          en: "Connect the Plug to Start Charging",
          fr: "Brancher la prise pour commencer la charge",
          es: "Conecte el enchufe para iniciar la carga",
          langFor: "app",
        },
        "Enter password": {
          en: "Enter password",
          fr: "Entrez le mot de passe",
          es: "Introduce la contraseña",
          langFor: "app",
        },
        "Release Version": {
          en: "Release Version",
          fr: "Version de diffusion",
          es: "Versión de lanzamiento",
          langFor: "app",
        },
        "Version Name": {
          en: "Version Name",
          fr: "Nom de la version",
          es: "Nombre de la versión",
          langFor: "app",
        },
        "The charger supports RFID cards and EMV (credit/debit) cards for payments. All transactions are securely processed.":
          {
            en: "The charger supports RFID cards and EMV (credit/debit) cards for payments. All transactions are securely processed.",
            fr: "Le chargeur accepte les cartes RFID et EMV (crédit/débit). Toutes les transactions sont traitées en toute sécurité.",
            es: "El cargador acepta tarjetas RFID y tarjetas EMV (crédito/débito) para pagos. Todas las transacciones se procesan de forma segura.",
            langFor: "app",
          },
        "Activator app is for activation/reactivation of charger": {
          en: "Activator app is for activation/reactivation of charger",
          fr: "L'application Activator sert à l'activation/réactivation du chargeur",
          es: "La aplicación Activator es para activar/reactivar el cargador",
          langFor: "app",
        },
        csms_card_declined_do_not_retry: {
          en: "CARD DECLINED: DO NOT RETRY",
          fr: "CARTE REFUSÉE : NE PAS RÉESSAYER",
          es: "TARJETA RECHAZADA: NO REINTENTE",
          langFor: "csms",
        },
        cancellation_request_stored: {
          en: "Cancellation request stored. Will be processed when preauth completes.",
          fr: "Demande d'annulation enregistrée. Elle sera traitée une fois la pré-autorisation terminée.",
          es: "Solicitud de cancelación almacenada. Se procesará al completarse la preautorización.",
          langFor: "csms",
        },
        csms_request_failed_403: {
          en: "Request failed with status code 403",
          fr: "La demande a échoué avec le code d'état 403",
          es: "La solicitud falló con el código 403",
          langFor: "csms",
        },
        csms_cancelled_could_not_decrypt_track2: {
          en: "Cancelled: Could not decrypt track2",
          fr: "Annulé : Impossible de déchiffrer la track2",
          es: "Cancelado: No se pudo descifrar track 2",
          langFor: "csms",
        },
        csms_issuer_not_online: {
          en: "ISSUER NOT ONLINE",
          fr: "ÉMETTEUR HORS LIGNE",
          es: "EMISOR NO CONECTADO",
          langFor: "csms",
        },
        csms_card_not_supported: {
          en: "CARD NOT SUPPORTED",
          fr: "CARTE NON PRISE EN CHARGE",
          es: "TARJETA NO COMPATIBLE",
          langFor: "csms",
        },
        csms_declined_call_amex: {
          en: "DECLINED CALL AMEX",
          fr: "REFUSÉ : APPELEZ AMEX",
          es: "RECHAZADO LLAMAR A AMEX",
          langFor: "csms",
        },
        csms_invalid_cid_4dbc: {
          en: "INVALID CID 4DBC",
          fr: "CID INVALIDE 4DBC",
          es: "CID INVÁLIDO 4DBC",
          langFor: "csms",
        },
        csms_invalid_transaction: {
          en: "Invalid transaction",
          fr: "Transaction invalide",
          es: "Transacción inválida",
          langFor: "csms",
        },
        csms_no_preauth_found_for_store_order_transaction_id: {
          en: "No Pre-auth corresponds to the store Id and order Id and transaction Id entered",
          fr: "Aucune préautorisation ne correspond à l’identifiant de magasin, de commande et de transaction saisi",
          es: "Ninguna autorización previa corresponde al Id. de la tienda, o al Id. del pedido o al Id. de la transacción ingresados",
          langFor: "csms",
        },
        csms_transaction_invalid_data: {
          en: "Transaction has invalid data!",
          fr: "La transaction contient des données invalides !",
          es: "¡La transacción contiene datos inválidos!",
          langFor: "csms",
        },
        csms_usage_exceeded: {
          en: "USAGE EXCEEDED",
          fr: "UTILISATION DÉPASSÉE",
          es: "LÍMITE DE USO EXCEDIDO",
          langFor: "csms",
        },
        csms_transaction_payment_refunded: {
          en: "The payment for this transaction is refunded.",
          fr: "Le paiement de cette transaction a été remboursé.",
          es: "El pago de esta transacción ha sido reembolsado.",
          langFor: "csms",
        },
        csms_preauth_already_cancelled: {
          en: "Preauth for this transaction is already cancelled.",
          fr: "La préautorisation pour cette transaction est déjà annulée.",
          es: "La preautorización de esta transacción ya está cancelada.",
          langFor: "csms",
        },
        csms_transaction_payment_processed: {
          en: "The payment for this transaction has been processed.",
          fr: "Le paiement de cette transaction a été traité.",
          es: "El pago de esta transacción ha sido procesada.",
          langFor: "csms",
        },
        csms_transaction_amount_not_captured: {
          en: "The amount for this transaction has not yet been captured.",
          fr: "Le montant de cette transaction n’a pas encore été capturé.",
          es: "El monto de esta transacción aún no se ha capturado.",
          langFor: "csms",
        },
        csms_invalid_refund_request: {
          en: "Invalid Refund Request: Check transaction type or transaction id mismatch",
          fr: "Demande de remboursement invalide : vérifiez le type ou l''identifiant de la transaction",
          es: "Solicitud de reembolso inválida: Compruebe el tipo de transacción o el identificador de transacción inadecuado",
          langFor: "csms",
        },
        csms_refund_already_processed: {
          en: "The refund for this transaction has already been processed.",
          fr: "Le remboursement de cette transaction a déjà été effectué.",
          es: "El reembolso de esta transacción ha sido procesada.",
          langFor: "csms",
        },
        csms_refund_amount_exceeds_capture: {
          en: "The refund amount cannot exceed the captured amount.",
          fr: "Le montant du remboursement ne peut pas dépasser le montant capturé.",
          es: "El importe del reembolso no puede ser superior al importe capturado.",
          langFor: "csms",
        },
        csms_declined_card_cancelled: {
          en: "DECLINED: CARD CANCELLED",
          fr: "REFUSÉ : CARTE ANNULÉE",
          es: "RECHAZADO: TARJETA CANCELADA",
          langFor: "csms",
        },
        csms_retry_edit_error: {
          en: "RE-TRY: EDIT ERROR",
          fr: "NOUVEL ESSAI : ERREUR DE MODIFICATION",
          es: "REINTENTAR: ERROR DE EDICIÓN",
          langFor: "csms",
        },
        csms_retry_system_problem: {
          en: "RE-TRY: SYSTEM PROBLEM",
          fr: "NOUVEL ESSAI : PROBLÈME SYSTÈME",
          es: "REINTENTAR: PROBLEMA DEL SISTEMA",
          langFor: "csms",
        },
        csms_cancelled_null: {
          en: "Cancelled: null",
          fr: "Annulé : nul",
          es: "Cancelado: anulado",
          langFor: "csms",
        },
        csms_payment_provider_required: {
          en: "Payment provider is required.",
          fr: "Le fournisseur de paiement est requis.",
          es: "Se requiere proveedor de pago.",
          langFor: "csms",
        },
        csms_invalid_payment_provider: {
          en: "Invalid payment provider.",
          fr: "Fournisseur de paiement invalide.",
          es: "Proveedor de pago inválido.",
          langFor: "csms",
        },
        csms_reversal_not_supported_moneris: {
          en: "Reversal is not supported for Moneris.",
          fr: "L’annulation n’est pas prise en charge pour Moneris.",
          es: "La reversión no es compatible con Moneris.",
          langFor: "csms",
        },
        csms_charger_not_found: {
          en: "Charger not found.",
          fr: "Borne de recharge introuvable.",
          es: "Cargador no encontrado.",
          langFor: "csms",
        },
        csms_payment_device_id_not_found: {
          en: "PaymentDeviceId not found in payment configuration.",
          fr: "PaymentDeviceId introuvable dans la configuration de paiement.",
          es: "PaymentDeviceId no se encuentra en la configuración de pago.",
          langFor: "csms",
        },
        csms_payment_provider_mismatch: {
          en: "Payment provider does not match the payment configuration.",
          fr: "Le fournisseur de paiement ne correspond pas à la configuration de paiement.",
          es: "El proveedor de pagos no coincide con la configuración de pago.",
          langFor: "csms",
        },
        csms_mfg_id_mismatch: {
          en: "mfg_Id from readerConfig does not match paymentMfgId from payment configuration.",
          fr: "mfg_Id de readerConfig ne correspond pas à paymentMfgId de la configuration de paiement.",
          es: "mfg_Id de readerConfig no coincide con paymentMfgId de la configuración.",
          langFor: "csms",
        },
        csms_request_failed: {
          en: "Request failed.",
          fr: "la demande a échoué",
          es: "La solicitud falló.",
          langFor: "csms",
        },
        csms_ocpp_transaction_not_found: {
          en: "OCPP Transaction not found.",
          fr: "Transaction OCPP introuvable.",
          es: "Transacción OCPP no encontrada.",
          langFor: "csms",
        },
        csms_invalid_pan_or_order_id: {
          en: "Invalid PAN or order ID.",
          fr: "PAN ou ID de commande invalide.",
          es: "PAN o ID de orden inválido.",
          langFor: "csms",
        },
        csms_preauth_ref_id_not_found: {
          en: "PreauthRefId not found.",
          fr: "PreauthRefId introuvable.",
          es: "PreauthRefId no encontrado.",
          langFor: "csms",
        },
        csms_emv_data_added_successfully: {
          en: "Successfully added emv_data",
          fr: "Données EMV ajoutées avec succès.",
          es: "Datos emv agregados exitosamente",
          langFor: "csms",
        },
        csms_approved_uppercase: {
          en: "APPROVED",
          fr: "APPROUVÉ",
          es: "APROBADO",
          langFor: "csms",
        },
        csms_approved: {
          en: "Approved",
          fr: "Approuvé",
          es: "Aprobado",
          langFor: "csms",
        },
        csms_invalid_amount_parameter: {
          en: "invalid amount parameter:10",
          fr: "paramètre de montant invalide :10",
          es: "parámetro de monto inválido:10",
          langFor: "csms",
        },
        csms_declined_uppercase: {
          en: "DECLINED",
          fr: "REFUSÉ",
          es: "RECHAZADO",
          langFor: "csms",
        },
        csms_request_failed_409: {
          en: "Request failed with status code 409",
          fr: "La requête a échoué avec le code d'état 409",
          es: "La solicitud falló con el código 409",
          langFor: "csms",
        },
        csms_request_failed_500: {
          en: "Request failed with status code 500",
          fr: "La requête a échoué avec le code d'état 500",
          es: "La solicitud falló con el código 500",
          langFor: "csms",
        },
        csms_request_failed_400: {
          en: "Request failed with status code 400",
          fr: "La requête a échoué avec le code d'état 400",
          es: "La solicitud falló con el código 400",
          langFor: "csms",
        },
        csms_transaction_timeout: {
          en: "Transaction Not Completed  Timed Out",
          fr: "Transaction non terminée – délai dépassé",
          es: "Transacción no completada: tiempo agotado",
          langFor: "csms",
        },
        csms_transaction_timeout_2: {
          en: "Transaction Not Completed Timed Out",
          fr: "Transaction non terminée – délai dépassé",
          es: "Transacción no completada: tiempo agotado",
          langFor: "csms",
        },
        csms_authorised_uppercase: {
          en: "AUTHORISED",
          fr: "AUTORISÉ",
          es: "AUTORIZADO",
          langFor: "csms",
        },
        csms_invalid_amount_parameter_1: {
          en: "invalid amount parameter:1",
          fr: "paramètre de montant invalide :1",
          es: "parámetro de monto inválido:1",
          langFor: "csms",
        },
        csms_transaction_captured: {
          en: "This Transaction is Captured.",
          fr: "Cette transaction est capturée.",
          es: "Esta transacción está capturada.",
          langFor: "csms",
        },
        csms_request_failed_404: {
          en: "Request failed with status code 404",
          fr: "La demande a échoué avec le code d'état 404",
          es: "La solicitud falló con el código 404",
          langFor: "csms",
        },
        feedback_charging_speed: {
          en: "Charging Speed",
          fr: "Vitesse de chargement",
          es: "Velocidad de carga",
          langFor: "feedback",
        },
        feedback_payment_experience: {
          en: "Payment Experience",
          fr: "Expérience de paiement",
          es: "Experiencia de pago",
          langFor: "feedback",
        },
        feedback_plug_or_connector_quality: {
          en: "Plug or Connector Quality",
          fr: "Qualité de la prise ou du connecteur",
          es: "Calidad del enchufe o conector",
          langFor: "feedback",
        },
        feedback_charging_cost: {
          en: "Charging Cost",
          fr: "Coût de chargement",
          es: "Costo de carga",
          langFor: "feedback",
        },
        feedback_customer_support: {
          en: "Customer Support",
          fr: "Assistance à la clientèle",
          es: "Atención al cliente",
          langFor: "feedback",
        },
        feedback_station_cleanliness: {
          en: "Station Cleanliness",
          fr: "Propreté de la station",
          es: "Limpieza de la estación",
          langFor: "feedback",
        },
        feedback_ease_of_use: {
          en: "Ease of Use",
          fr: "Facilité d'utilisation",
          es: "Facilidad de uso",
          langFor: "feedback",
        },
        invoice_receipt: {
          en: "Receipt",
          fr: "Reçu",
          es: "Recibo",
          langFor: "invoice",
        },
        invoice_receipt_caps: {
          en: "RECEIPT",
          fr: "REÇU",
          es: "RECIBO",
          langFor: "invoice",
        },
        invoice_receipt_msg: {
          en: "Here's your receipt for your charging session.",
          fr: "Voici votre reçu pour votre session de recharge.",
          es: "Aquí está su recibo por la sesión de carga.",
          langFor: "invoice",
        },
        invoice_receipt_number: {
          en: "Receipt Number",
          fr: "Numéro de reçu",
          es: "Número de recibo",
          langFor: "invoice",
        },
        invoice_issue_date_time: {
          en: "Date of Issue and Time",
          fr: "Date et heure d'émission",
          es: "Fecha y hora de emisión",
          langFor: "invoice",
        },
        invoice_transaction_id: {
          en: "Transaction ID",
          fr: "ID de transaction",
          es: "ID de transacción",
          langFor: "invoice",
        },
        invoice_type: {
          en: "Type",
          fr: "Type",
          es: "Tipo",
          langFor: "invoice",
        },
        invoice_card_scheme: {
          en: "Card System",
          fr: "Réseau de carte",
          es: "Esquema de tarjeta",
          langFor: "invoice",
        },
        invoice_card_number: {
          en: "Card Number",
          fr: "Numéro de carte",
          es: "Número de tarjeta",
          langFor: "invoice",
        },
        invoice_reference_no: {
          en: "Reference #",
          fr: "N° de référence",
          es: "Referencia #",
          langFor: "invoice",
        },
        invoice_auth_no: {
          en: "Authorization No.",
          fr: "N° d'autorisation",
          es: "Autorización #",
          langFor: "invoice",
        },
        invoice_charger_details: {
          en: "Charger Details EVSE Station",
          fr: "Détails du chargeur Station EVSE",
          es: "Detalles del cargador Estación EVSE",
          langFor: "invoice",
        },
        invoice_chargebox_id: {
          en: "Chargebox ID",
          fr: "ID de la borne",
          es: "ID de caja de carga",
          langFor: "invoice",
        },
        invoice_charging_summary: {
          en: "Charging Session Summary",
          fr: "Résumé de la session de charge",
          es: "Resumen de la sesión de carga",
          langFor: "invoice",
        },
        invoice_charging_time: {
          en: "Charging time",
          fr: "Temps de charge",
          es: "Tiempo de carga",
          langFor: "invoice",
        },
        invoice_session_id: {
          en: "Session ID",
          fr: "ID de session",
          es: "ID de la sesión",
          langFor: "invoice",
        },
        invoice_duration: {
          en: "Duration(hrs)",
          fr: "Durée(heures)",
          es: "Duración(horas)",
          langFor: "invoice",
        },
        invoice_energy_used: {
          en: "Energy Used(kWh)",
          fr: "Énergie utilisée(kWh)",
          es: "Energía consumida (kWh)",
          langFor: "invoice",
        },
        invoice_from: {
          en: "From",
          fr: "De",
          es: "De",
          langFor: "invoice",
        },
        invoice_to: {
          en: "To",
          fr: "À",
          es: "A",
          langFor: "invoice",
        },
        invoice_billing_summary: {
          en: "Billing Summary",
          fr: "Résumé de facturation",
          es: "Resumen de facturación",
          langFor: "invoice",
        },
        invoice_description: {
          en: "Description",
          fr: "Description",
          es: "Descripción",
          langFor: "invoice",
        },
        invoice_energy: {
          en: "Energy",
          fr: "Énergie",
          es: "Energía",
          langFor: "invoice",
        },
        invoice_total: {
          en: "Total",
          fr: "Total",
          es: "Total",
          langFor: "invoice",
        },
        invoice_unit_price: {
          en: "Unit Price",
          fr: "Prix unitaire",
          es: "Precio unitario",
          langFor: "invoice",
        },
        invoice_amount: {
          en: "Amount",
          fr: "Montant",
          es: "Importe",
          langFor: "invoice",
        },
        invoice_consumed_kwh: {
          en: "Consumed (kWh)",
          fr: "Consommé (kWh)",
          es: "Consumido (kWh)",
          langFor: "invoice",
        },
        invoice_parking_rate: {
          en: "Parking Rate (hrs)",
          fr: "Tarif de stationnement (heures)",
          es: "Tarifa de estacionamiento (horas)",
          langFor: "invoice",
        },
        invoice_peak_charges: {
          en: "Peak(or offpeak) Charges (hrs)",
          fr: "Frais de pointe (ou hors pointe) (heures)",
          es: "Cargos por horas pico (o valle)",
          langFor: "invoice",
        },
        invoice_subtotal: {
          en: "Sub Total",
          fr: "Sous-total",
          es: "Subtotal",
          langFor: "invoice",
        },
        invoice_discount: {
          en: "Discount",
          fr: "Rabais",
          es: "Descuento",
          langFor: "invoice",
        },
        invoice_penalty: {
          en: "Penalty",
          fr: "Pénalité",
          es: "Penalización / Multa",
          langFor: "invoice",
        },
        invoice_taxable_amount: {
          en: "Taxable Amount",
          fr: "Montant taxable",
          es: "Monto imponible",
          langFor: "invoice",
        },
        invoice_tax: {
          en: "Tax",
          fr: "Taxe",
          es: "Impuesto",
          langFor: "invoice",
        },
        invoice_total_amount: {
          en: "Total Amount",
          fr: "Montant total",
          es: "Monto total",
          langFor: "invoice",
        },
        invoice_thank_you: {
          en: "Thank you",
          fr: "Merci",
          es: "Gracias",
          langFor: "invoice",
        },
        invoice_no_signature: {
          en: "NO SIGNATURE REQUIRED",
          fr: "AUCUNE SIGNATURE REQUISE",
          es: "NO SE REQUIERE FIRMA",
          langFor: "invoice",
        },
        invoice_cardholder_agreement_prefix: {
          en: "CARDHOLDER WILL PAY CARD ISSUER ABOVE AMOUNT PURSUANT TO",
          fr: "LE TITULAIRE DE LA CARTE PAIERA LE MONTANT CI-DESSUS À L'ÉMETTEUR CONFORMÉMENT À",
          es: "EL TITULAR DE LA TARJETA PAGARÁ AL EMISOR EL MONTO ANTERIOR CONFORME A",
          langFor: "invoice",
        },
        invoice_cardholder_agreement: {
          en: "CARDHOLDER AGREEMENT",
          fr: "CONTRAT DU TITULAIRE DE CARTE",
          es: "CONTRATO DEL TITULAR DE LA TARJETA",
          langFor: "invoice",
        },
        invoice_pre_auth_complete: {
          en: "Pre Auth Complete",
          fr: "Pré-autorisation terminée",
          es: "Preautorización completada",
          langFor: "invoice",
        },
      };

      const result = Object.entries(langData).map(([key, value]) => ({
        langKey: key,
        ...value,
      }));

      await LanguageRepository.save(result);
      console.log("Language seeding done.");
    }
  } catch (error) {
    console.error("Error seeding ChargeUsageType in database:", error);
  }
};

module.exports = { SeedLanguage };
