const mongoose = require("mongoose");
const {
  BootNotificationModel,
  ChargingSessionLogModel,
  ChargerRapidLogsModel,
  ConnectedChargerModel,
  CountryModel,
  EmailLogModel,
  NotificationModel,
  OcppBootNotificationLogModel,
  OcppHeartbeatLogModel,
  OcppLogModel,
  OcppMeterValueLogModel,
  OcppTransactionLogModel,
  PusherLogModel,
  SessionModel,
  SessionView,
  TransactionModel,
  TransactionView,
  WebhookModel,
  WebhookLogModel,
  DeviceOverviewModel,
  AgentConcurrencyModel,
  RemoteCommandTrackerModel,
  RolloutModel,
  RolloutDeviceStatesModel,
  RolloutDeviceStatesHistoryModel,
  StorageMonthlyModel,
  StorageDeviceMonthlyModel,
  OcppAllLogView,
  PaymentAuthorizeModel,
  PaymentCaptureModel,
  DiscoverChargerLogModel,
  PreauthLogsModel,
  PurchaseLogsModel,
  UtilizationRateModel,
  EmvDataAddLogsModel,
  PreauthCompleteLogsModel,
  RefundLogsModel,
  TransactionHistoryViewModel,
  TransactionErrorLogsModel,
  AnalyticsModel,
  AutoCaptureLogsModel,
  ApiErrorLogsModel,
  CronSchedulerModel,
  PreauthCancelLogsModel,
  MessagesToTranslateModel,
  PendingCancellationLogsModel,
  IpDataModel,
  ActionOtpModel,
  AuropayWebhookModel,
  ExternalOcppConnectionModel,
  ExternalOcppLogModel,
  ChargerConfigurationModel,
  OcppAllLogModel,
  PaynexWebhookModel,
  WhatsappWebhookLogsModel,
} = require("./models");

require("dotenv").config({ path: process.env.ENV_FILE || ".env" });

const initializeMongoDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_DB_URL);
    console.log("MongoDB connected successfully.");
  } catch (error) {
    console.error("MongoDB connection error:", error);
    throw error;
  }
};

module.exports = {
  initializeMongoDB,
  BootNotificationModel,
  ChargingSessionLogModel,
  ChargerRapidLogsModel,
  ConnectedChargerModel,
  CountryModel,
  EmailLogModel,
  NotificationModel,
  OcppBootNotificationLogModel,
  OcppHeartbeatLogModel,
  OcppLogModel,
  OcppMeterValueLogModel,
  OcppTransactionLogModel,
  PusherLogModel,
  SessionModel,
  SessionView,
  TransactionModel,
  TransactionView,
  WebhookModel,
  WebhookLogModel,
  DeviceOverviewModel,
  AgentConcurrencyModel,
  RemoteCommandTrackerModel,
  RolloutModel,
  RolloutDeviceStatesModel,
  RolloutDeviceStatesHistoryModel,
  StorageMonthlyModel,
  StorageDeviceMonthlyModel,
  OcppAllLogView,
  PaymentAuthorizeModel,
  PaymentCaptureModel,
  DiscoverChargerLogModel,
  PreauthLogsModel,
  PurchaseLogsModel,
  UtilizationRateModel,
  EmvDataAddLogsModel,
  PreauthCompleteLogsModel,
  RefundLogsModel,
  TransactionHistoryViewModel,
  TransactionErrorLogsModel,
  AnalyticsModel,
  AutoCaptureLogsModel,
  ApiErrorLogsModel,
  CronSchedulerModel,
  PreauthCancelLogsModel,
  MessagesToTranslateModel,
  PendingCancellationLogsModel,
  IpDataModel,
  ActionOtpModel,
  AuropayWebhookModel,
  ExternalOcppConnectionModel,
  ExternalOcppLogModel,
  ChargerConfigurationModel,
  OcppAllLogModel,
  PaynexWebhookModel,
  WhatsappWebhookLogsModel,
};
