const LocalizationCodeData = [
  {
    country_name: "Argentina",
    country_code_alpha: "ARG",
    country_code_numeric: "32",
    currency_code_alpha: "ARS",
    currency_code_numeric: "32",
    dial_code: "54",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:AR",
    iso_code: "AR",
  },
  {
    country_name: "Mali",
    country_code_alpha: "MLI",
    country_code_numeric: "466",
    currency_code_alpha: "XOF",
    currency_code_numeric: "952",
    dial_code: "223",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:MV",
    iso_code: "ML",
  },
  {
    country_name: "India",
    country_code_alpha: "IND",
    country_code_numeric: "356",
    currency_code_alpha: "INR",
    currency_code_numeric: "356",
    dial_code: "91",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:IS",
    iso_code: "IN",
  },
  {
    country_name: "Greenland",
    country_code_alpha: "GRL",
    country_code_numeric: "304",
    currency_code_alpha: "DKK",
    currency_code_numeric: "208",
    dial_code: "299",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:GR",
    iso_code: "GL",
  },
  {
    country_name: "Netherlands",
    country_code_alpha: "NLD",
    country_code_numeric: "528",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "31",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:NP",
    iso_code: "NL",
  },
  {
    country_name: "Finland",
    country_code_alpha: "FIN",
    country_code_numeric: "246",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "358",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:FJ",
    iso_code: "FI",
  },
  {
    country_name: "Norway",
    country_code_alpha: "NOR",
    country_code_numeric: "578",
    currency_code_alpha: "NOK",
    currency_code_numeric: "578",
    dial_code: "47",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:MP",
    iso_code: "NO",
  },
  {
    country_name: "Korea, Republic of",
    country_code_alpha: "KOR",
    country_code_numeric: "410",
    currency_code_alpha: "KRW",
    currency_code_numeric: "410",
    dial_code: "82",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:KP",
    iso_code: "KR",
  },
  {
    country_name: "Greece",
    country_code_alpha: "GRC",
    country_code_numeric: "300",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "30",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:GI",
    iso_code: "GR",
  },
  {
    country_name: "Norfolk Island",
    country_code_alpha: "NFK",
    country_code_numeric: "574",
    currency_code_alpha: "AUD",
    currency_code_numeric: "36",
    dial_code: "672",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:NU",
    iso_code: "NF",
  },
  {
    country_name: "Saint Helena, Ascension and Tristan da Cunha",
    country_code_alpha: "SHN",
    country_code_numeric: "654",
    currency_code_alpha: "SHP",
    currency_code_numeric: "654",
    dial_code: "290",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:BL",
    iso_code: "SH",
  },
  {
    country_name: "Uganda",
    country_code_alpha: "UGA",
    country_code_numeric: "800",
    currency_code_alpha: "UGX",
    currency_code_numeric: "800",
    dial_code: "256",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:UG",
    iso_code: "UG",
  },
  {
    country_name: "Mauritius",
    country_code_alpha: "MUS",
    country_code_numeric: "480",
    currency_code_alpha: "MUR",
    currency_code_numeric: "480",
    dial_code: "230",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:MR",
    iso_code: "MU",
  },
  {
    country_name: "North Macedonia",
    country_code_alpha: "MKD",
    country_code_numeric: "807",
    currency_code_alpha: "MKD",
    currency_code_numeric: "807",
    dial_code: "389",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:NF",
    iso_code: "MK",
  },
  {
    country_name: "Hong Kong",
    country_code_alpha: "HKG",
    country_code_numeric: "344",
    currency_code_alpha: "HKD",
    currency_code_numeric: "344",
    dial_code: "852",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:HN",
    iso_code: "HK",
  },
  {
    country_name: "French Guiana",
    country_code_alpha: "GUF",
    country_code_numeric: "254",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "594",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:FR",
    iso_code: "GF",
  },
  {
    country_name: "Tanzania",
    country_code_alpha: "TZA",
    country_code_numeric: "834",
    currency_code_alpha: "TZS",
    currency_code_numeric: "834",
    dial_code: "255",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:TH",
    iso_code: "TZ",
  },
  {
    country_name: "Curaçao",
    country_code_alpha: "CUW",
    country_code_numeric: "531",
    currency_code_alpha: "ANG",
    currency_code_numeric: "533",
    dial_code: "599",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:CU",
    iso_code: "CW",
  },
  {
    country_name: "Morocco",
    country_code_alpha: "MAR",
    country_code_numeric: "504",
    currency_code_alpha: "MAD",
    currency_code_numeric: "504",
    dial_code: "212",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:MS",
    iso_code: "MA",
  },
  {
    country_name: "Spain",
    country_code_alpha: "ESP",
    country_code_numeric: "724",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "34",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:ES",
    iso_code: "ES",
  },
  {
    country_name: "Guernsey",
    country_code_alpha: "GGY",
    country_code_numeric: "831",
    currency_code_alpha: "GGP",
    currency_code_numeric: "831",
    dial_code: "44",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:GT",
    iso_code: "GG",
  },
  {
    country_name: "Micronesia, Federated States of",
    country_code_alpha: "FSM",
    country_code_numeric: "583",
    currency_code_alpha: "USD",
    currency_code_numeric: "840",
    dial_code: "691",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:MX",
    iso_code: "FM",
  },
  {
    country_name: "Bhutan",
    country_code_alpha: "BTN",
    country_code_numeric: "64",
    currency_code_alpha: "BTN",
    currency_code_numeric: "64",
    dial_code: "975",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:BT",
    iso_code: "BT",
  },
  {
    country_name: "Myanmar",
    country_code_alpha: "MMR",
    country_code_numeric: "104",
    currency_code_alpha: "MMK",
    currency_code_numeric: "104",
    dial_code: "95",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:MZ",
    iso_code: "MM",
  },
  {
    country_name: "Panama",
    country_code_alpha: "PAN",
    country_code_numeric: "591",
    currency_code_alpha: "PAB",
    currency_code_numeric: "591",
    dial_code: "507",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:PS",
    iso_code: "PA",
  },
  {
    country_name: "Armenia",
    country_code_alpha: "ARM",
    country_code_numeric: "51",
    currency_code_alpha: "AMD",
    currency_code_numeric: "51",
    dial_code: "374",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:AM",
    iso_code: "AM",
  },
  {
    country_name: "Montserrat",
    country_code_alpha: "MSR",
    country_code_numeric: "500",
    currency_code_alpha: "XCD",
    currency_code_numeric: "951",
    dial_code: "1",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:ME",
    iso_code: "MS",
  },
  {
    country_name: "Cambodia",
    country_code_alpha: "KHM",
    country_code_numeric: "116",
    currency_code_alpha: "KHR",
    currency_code_numeric: "116",
    dial_code: "855",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:CV",
    iso_code: "KH",
  },
  {
    country_name: "Niger",
    country_code_alpha: "NER",
    country_code_numeric: "562",
    currency_code_alpha: "XOF",
    currency_code_numeric: "952",
    dial_code: "227",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:NI",
    iso_code: "NE",
  },
  {
    country_name: "Guinea-Bissau",
    country_code_alpha: "GNB",
    country_code_numeric: "624",
    currency_code_alpha: "GNB",
    currency_code_numeric: "624",
    dial_code: "245",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:GN",
    iso_code: "GW",
  },
  {
    country_name: "Bermuda",
    country_code_alpha: "BMU",
    country_code_numeric: "60",
    currency_code_alpha: "BMD",
    currency_code_numeric: "60",
    dial_code: "1",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:BM",
    iso_code: "BM",
  },
  {
    country_name: "Mauritania",
    country_code_alpha: "MRT",
    country_code_numeric: "478",
    currency_code_alpha: "MRU",
    currency_code_numeric: "478",
    dial_code: "222",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:MQ",
    iso_code: "MR",
  },
  {
    country_name: "New Zealand",
    country_code_alpha: "NZL",
    country_code_numeric: "554",
    currency_code_alpha: "NZD",
    currency_code_numeric: "554",
    dial_code: "64",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:NC",
    iso_code: "NZ",
  },
  {
    country_name: "Tunisia",
    country_code_alpha: "TUN",
    country_code_numeric: "788",
    currency_code_alpha: "TND",
    currency_code_numeric: "788",
    dial_code: "216",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:TR",
    iso_code: "TN",
  },
  {
    country_name: "Suriname",
    country_code_alpha: "SUR",
    country_code_numeric: "740",
    currency_code_alpha: "SRD",
    currency_code_numeric: "740",
    dial_code: "597",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:SR",
    iso_code: "SR",
  },
  {
    country_name: "Botswana",
    country_code_alpha: "BWA",
    country_code_numeric: "72",
    currency_code_alpha: "BWP",
    currency_code_numeric: "72",
    dial_code: "267",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:BA",
    iso_code: "BW",
  },
  {
    country_name: "Bangladesh",
    country_code_alpha: "BGD",
    country_code_numeric: "50",
    currency_code_alpha: "BDT",
    currency_code_numeric: "50",
    dial_code: "880",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:BD",
    iso_code: "BD",
  },
  {
    country_name: "Ghana",
    country_code_alpha: "GHA",
    country_code_numeric: "288",
    currency_code_alpha: "GHS",
    currency_code_numeric: "288",
    dial_code: "233",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:DE",
    iso_code: "GH",
  },
  {
    country_name: "Gambia",
    country_code_alpha: "GMB",
    country_code_numeric: "270",
    currency_code_alpha: "GMD",
    currency_code_numeric: "270",
    dial_code: "220",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:GA",
    iso_code: "GM",
  },
  {
    country_name: "Cameroon",
    country_code_alpha: "CMR",
    country_code_numeric: "120",
    currency_code_alpha: "XAF",
    currency_code_numeric: "950",
    dial_code: "237",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:KH",
    iso_code: "CM",
  },
  {
    country_name: "South Georgia and the South Sandwich Islands",
    country_code_alpha: "SGS",
    country_code_numeric: "239",
    currency_code_alpha: "GBP",
    currency_code_numeric: "826",
    dial_code: "500",
    region: "Antarctica",
    iso_3166_2: "ISO 3166-2:GS",
    iso_code: "GS",
  },
  {
    country_name: "Seychelles",
    country_code_alpha: "SYC",
    country_code_numeric: "690",
    currency_code_alpha: "SCR",
    currency_code_numeric: "690",
    dial_code: "248",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:RS",
    iso_code: "SC",
  },
  {
    country_name: "Brazil",
    country_code_alpha: "BRA",
    country_code_numeric: "76",
    currency_code_alpha: "BRL",
    currency_code_numeric: "986",
    dial_code: "55",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:BV",
    iso_code: "BR",
  },
  {
    country_name: "Lesotho",
    country_code_alpha: "LES",
    country_code_numeric: "426",
    currency_code_alpha: "LSL",
    currency_code_numeric: "426",
    dial_code: "266",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:LB",
    iso_code: "LS",
  },
  {
    country_name: "Tajikistan",
    country_code_alpha: "TJK",
    country_code_numeric: "762",
    currency_code_alpha: "TJS",
    currency_code_numeric: "762",
    dial_code: "992",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:TZ",
    iso_code: "TJ",
  },
  {
    country_name: "South Sudan",
    country_code_alpha: "SSD",
    country_code_numeric: "728",
    currency_code_alpha: "SSP",
    currency_code_numeric: "728",
    dial_code: "211",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:SS",
    iso_code: "SS",
  },
  {
    country_name: "Lebanon",
    country_code_alpha: "LBN",
    country_code_numeric: "422",
    currency_code_alpha: "LBP",
    currency_code_numeric: "422",
    dial_code: "961",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:LV",
    iso_code: "LB",
  },
  {
    country_name: "Guinea",
    country_code_alpha: "GIN",
    country_code_numeric: "324",
    currency_code_alpha: "GNF",
    currency_code_numeric: "324",
    dial_code: "224",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:GG",
    iso_code: "GN",
  },
  {
    country_name: "China",
    country_code_alpha: "CHN",
    country_code_numeric: "156",
    currency_code_alpha: "CNY",
    currency_code_numeric: "156",
    dial_code: "86",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:CL",
    iso_code: "CN",
  },
  {
    country_name: "Isle of Man",
    country_code_alpha: "IMN",
    country_code_numeric: "833",
    currency_code_alpha: "GBP",
    currency_code_numeric: "826",
    dial_code: "44",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:IE",
    iso_code: "IM",
  },
  {
    country_name: "Guatemala",
    country_code_alpha: "GTM",
    country_code_numeric: "320",
    currency_code_alpha: "GTQ",
    currency_code_numeric: "320",
    dial_code: "502",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:GU",
    iso_code: "GT",
  },
  {
    country_name: "Solomon Islands",
    country_code_alpha: "SLB",
    country_code_numeric: "90",
    currency_code_alpha: "SBD",
    currency_code_numeric: "90",
    dial_code: "677",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:SB",
    iso_code: "SB",
  },
  {
    country_name: "New Caledonia",
    country_code_alpha: "NCL",
    country_code_numeric: "540",
    currency_code_alpha: "XPF",
    currency_code_numeric: "953",
    dial_code: "687",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:NL",
    iso_code: "NC",
  },
  {
    country_name: "Nicaragua",
    country_code_alpha: "NIC",
    country_code_numeric: "558",
    currency_code_alpha: "NIO",
    currency_code_numeric: "558",
    dial_code: "505",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:NZ",
    iso_code: "NI",
  },
  {
    country_name: "Barbados",
    country_code_alpha: "BRB",
    country_code_numeric: "52",
    currency_code_alpha: "BBD",
    currency_code_numeric: "52",
    dial_code: "1",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:BB",
    iso_code: "BB",
  },
  {
    country_name: "Kazakhstan",
    country_code_alpha: "KAZ",
    country_code_numeric: "398",
    currency_code_alpha: "KZT",
    currency_code_numeric: "398",
    dial_code: "7",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:JO",
    iso_code: "KZ",
  },
  {
    country_name: "Sri Lanka",
    country_code_alpha: "LKA",
    country_code_numeric: "144",
    currency_code_alpha: "LKR",
    currency_code_numeric: "144",
    dial_code: "94",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:LK",
    iso_code: "LK",
  },
  {
    country_name: "Jersey",
    country_code_alpha: "JEY",
    country_code_numeric: "832",
    currency_code_alpha: "GBP",
    currency_code_numeric: "826",
    dial_code: "44",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:JP",
    iso_code: "JE",
  },
  {
    country_name: "Nigeria",
    country_code_alpha: "NGA",
    country_code_numeric: "566",
    currency_code_alpha: "NGN",
    currency_code_numeric: "566",
    dial_code: "234",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:NE",
    iso_code: "NG",
  },
  {
    country_name: "Taiwan",
    country_code_alpha: "TWN",
    country_code_numeric: "158",
    currency_code_alpha: "TWD",
    currency_code_numeric: "158",
    dial_code: "886",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:TJ",
    iso_code: "TW",
  },
  {
    country_name: "Israel",
    country_code_alpha: "ISR",
    country_code_numeric: "376",
    currency_code_alpha: "ILS",
    currency_code_numeric: "376",
    dial_code: "972",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:IM",
    iso_code: "IL",
  },
  {
    country_name: "Niue",
    country_code_alpha: "NIU",
    country_code_numeric: "570",
    currency_code_alpha: "NZD",
    currency_code_numeric: "554",
    dial_code: "683",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:NG",
    iso_code: "NU",
  },
  {
    country_name: "Italy",
    country_code_alpha: "ITA",
    country_code_numeric: "380",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "39",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:IL",
    iso_code: "IT",
  },
  {
    country_name: "São Tomé and Príncipe",
    country_code_alpha: "STP",
    country_code_numeric: "678",
    currency_code_alpha: "STN",
    currency_code_numeric: "678",
    dial_code: "239",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:SM",
    iso_code: "ST",
  },
  {
    country_name: "Bulgaria",
    country_code_alpha: "BGR",
    country_code_numeric: "100",
    currency_code_alpha: "BGN",
    currency_code_numeric: "100",
    dial_code: "359",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:BN",
    iso_code: "BG",
  },
  {
    country_name: "Liberia",
    country_code_alpha: "LBR",
    country_code_numeric: "430",
    currency_code_alpha: "LRD",
    currency_code_numeric: "430",
    dial_code: "231",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:LS",
    iso_code: "LR",
  },
  {
    country_name: "Papua New Guinea",
    country_code_alpha: "PNG",
    country_code_numeric: "598",
    currency_code_alpha: "PGK",
    currency_code_numeric: "598",
    dial_code: "675",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:PA",
    iso_code: "PG",
  },
  {
    country_name: "Korea, Democratic People's Republic of",
    country_code_alpha: "PRK",
    country_code_numeric: "408",
    currency_code_alpha: "KPW",
    currency_code_numeric: "408",
    dial_code: "850",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:KI",
    iso_code: "KP",
  },
  {
    country_name: "Belgium",
    country_code_alpha: "BEL",
    country_code_numeric: "56",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "32",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:BE",
    iso_code: "BE",
  },
  {
    country_name: "Côte d'Ivoire",
    country_code_alpha: "CIV",
    country_code_numeric: "384",
    currency_code_alpha: "XOF",
    currency_code_numeric: "952",
    dial_code: "225",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:CR",
    iso_code: "CI",
  },
  {
    country_name: "Burundi",
    country_code_alpha: "BDI",
    country_code_numeric: "108",
    currency_code_alpha: "BIF",
    currency_code_numeric: "108",
    dial_code: "257",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:BF",
    iso_code: "BI",
  },
  {
    country_name: "American Samoa",
    country_code_alpha: "ASM",
    country_code_numeric: "16",
    currency_code_alpha: "USD",
    currency_code_numeric: "840",
    dial_code: "1",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:AS",
    iso_code: "AS",
  },
  {
    country_name: "Paraguay",
    country_code_alpha: "PRY",
    country_code_numeric: "600",
    currency_code_alpha: "PYG",
    currency_code_numeric: "600",
    dial_code: "595",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:PG",
    iso_code: "PY",
  },
  {
    country_name: "Colombia",
    country_code_alpha: "COL",
    country_code_numeric: "170",
    currency_code_alpha: "COP",
    currency_code_numeric: "170",
    dial_code: "57",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:CC",
    iso_code: "CO",
  },
  {
    country_name: "Bosnia and Herzegovina",
    country_code_alpha: "BIH",
    country_code_numeric: "70",
    currency_code_alpha: "BAM",
    currency_code_numeric: "977",
    dial_code: "387",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:BQ",
    iso_code: "BA",
  },
  {
    country_name: "Togo",
    country_code_alpha: "TGO",
    country_code_numeric: "768",
    currency_code_alpha: "XOF",
    currency_code_numeric: "952",
    dial_code: "228",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:TK",
    iso_code: "TG",
  },
  {
    country_name: "Malta",
    country_code_alpha: "MLT",
    country_code_numeric: "470",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "356",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:ML",
    iso_code: "MT",
  },
  {
    country_name: "Jamaica",
    country_code_alpha: "JAM",
    country_code_numeric: "388",
    currency_code_alpha: "JMD",
    currency_code_numeric: "388",
    dial_code: "1",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:IT",
    iso_code: "JM",
  },
  {
    country_name: "Costa Rica",
    country_code_alpha: "CRI",
    country_code_numeric: "188",
    currency_code_alpha: "CRC",
    currency_code_numeric: "188",
    dial_code: "506",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:CK",
    iso_code: "CR",
  },
  {
    country_name: "Puerto Rico",
    country_code_alpha: "PRI",
    country_code_numeric: "630",
    currency_code_alpha: "USD",
    currency_code_numeric: "840",
    dial_code: "1",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:PT",
    iso_code: "PR",
  },
  {
    country_name: "Afghanistan",
    country_code_alpha: "AFG",
    country_code_numeric: "4",
    currency_code_alpha: "AFN",
    currency_code_numeric: "971",
    dial_code: "93",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:AF",
    iso_code: "AF",
  },
  {
    country_name: "Nauru",
    country_code_alpha: "NRU",
    country_code_numeric: "520",
    currency_code_alpha: "AUD",
    currency_code_numeric: "36",
    dial_code: "674",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:NA",
    iso_code: "NR",
  },
  {
    country_name: "Saint Vincent and the Grenadines",
    country_code_alpha: "VCT",
    country_code_numeric: "670",
    currency_code_alpha: "XCD",
    currency_code_numeric: "951",
    dial_code: "1",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:PM",
    iso_code: "VC",
  },
  {
    country_name: "Monaco",
    country_code_alpha: "MCO",
    country_code_numeric: "492",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "377",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:MD",
    iso_code: "MC",
  },
  {
    country_name: "Liechtenstein",
    country_code_alpha: "LIE",
    country_code_numeric: "438",
    currency_code_alpha: "CHF",
    currency_code_numeric: "756",
    dial_code: "423",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:LY",
    iso_code: "LI",
  },
  {
    country_name: "Brunei Darussalam",
    country_code_alpha: "BRN",
    country_code_numeric: "96",
    currency_code_alpha: "BND",
    currency_code_numeric: "96",
    dial_code: "673",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:IO",
    iso_code: "BN",
  },
  {
    country_name: "Samoa",
    country_code_alpha: "WSM",
    country_code_numeric: "882",
    currency_code_alpha: "WST",
    currency_code_numeric: "882",
    dial_code: "685",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:VC",
    iso_code: "WS",
  },
  {
    country_name: "Algeria",
    country_code_alpha: "DZA",
    country_code_numeric: "12",
    currency_code_alpha: "DZD",
    currency_code_numeric: "12",
    dial_code: "213",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:DZ",
    iso_code: "DZ",
  },
  {
    country_name: "Saint Martin",
    country_code_alpha: "SPM",
    country_code_numeric: "663",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "590",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:LC",
    iso_code: "MF",
  },
  {
    country_name: "Rwanda",
    country_code_alpha: "RWA",
    country_code_numeric: "646",
    currency_code_alpha: "RWF",
    currency_code_numeric: "646",
    dial_code: "250",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:RU",
    iso_code: "RW",
  },
  {
    country_name: "Ukraine",
    country_code_alpha: "UKR",
    country_code_numeric: "804",
    currency_code_alpha: "UAH",
    currency_code_numeric: "804",
    dial_code: "380",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:UA",
    iso_code: "UA",
  },
  {
    country_name: "Faroe Islands",
    country_code_alpha: "FRO",
    country_code_numeric: "234",
    currency_code_alpha: "DKK",
    currency_code_numeric: "208",
    dial_code: "298",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:FK",
    iso_code: "FO",
  },
  {
    country_name: "Åland Islands",
    country_code_alpha: "ALA",
    country_code_numeric: "248",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "358",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:AX",
    iso_code: "AX",
  },
  {
    country_name: "Gabon",
    country_code_alpha: "GAB",
    country_code_numeric: "266",
    currency_code_alpha: "GAB",
    currency_code_numeric: "266",
    dial_code: "241",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:TF",
    iso_code: "GA",
  },
  {
    country_name: "Thailand",
    country_code_alpha: "THA",
    country_code_numeric: "764",
    currency_code_alpha: "THB",
    currency_code_numeric: "764",
    dial_code: "66",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:TL",
    iso_code: "TH",
  },
  {
    country_name: "Iran, Islamic Republic of",
    country_code_alpha: "IRN",
    country_code_numeric: "364",
    currency_code_alpha: "IRR",
    currency_code_numeric: "364",
    dial_code: "98",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:ID",
    iso_code: "IR",
  },
  {
    country_name: "Yemen",
    country_code_alpha: "YEM",
    country_code_numeric: "887",
    currency_code_alpha: "YER",
    currency_code_numeric: "887",
    dial_code: "967",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:WF",
    iso_code: "YE",
  },
  {
    country_name: "Haiti",
    country_code_alpha: "HTI",
    country_code_numeric: "332",
    currency_code_alpha: "HTG",
    currency_code_numeric: "332",
    dial_code: "509",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:GY",
    iso_code: "HT",
  },
  {
    country_name: "France",
    country_code_alpha: "FRA",
    country_code_numeric: "250",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "33",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:FI",
    iso_code: "FR",
  },
  {
    country_name: "Northern Mariana Islands",
    country_code_alpha: "MNP",
    country_code_numeric: "580",
    currency_code_alpha: "USD",
    currency_code_numeric: "840",
    dial_code: "1",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:MK",
    iso_code: "MP",
  },
  {
    country_name: "Russian Federation",
    country_code_alpha: "RUS",
    country_code_numeric: "643",
    currency_code_alpha: "RUB",
    currency_code_numeric: "643",
    dial_code: "7",
    region: "Europe/Asia",
    iso_3166_2: "ISO 3166-2:RO",
    iso_code: "RU",
  },
  {
    country_name: "Belize",
    country_code_alpha: "BLZ",
    country_code_numeric: "84",
    currency_code_alpha: "BZD",
    currency_code_numeric: "84",
    dial_code: "501",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:BZ",
    iso_code: "BZ",
  },
  {
    country_name: "Turkey",
    country_code_alpha: "TUR",
    country_code_numeric: "792",
    currency_code_alpha: "TRY",
    currency_code_numeric: "792",
    dial_code: "90",
    region: "Europe/Asia",
    iso_3166_2: "ISO 3166-2:TM",
    iso_code: "TR",
  },
  {
    country_name: "Portugal",
    country_code_alpha: "PRT",
    country_code_numeric: "620",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "351",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:PL",
    iso_code: "PT",
  },
  {
    country_name: "Saint Kitts and Nevis",
    country_code_alpha: "KNA",
    country_code_numeric: "659",
    currency_code_alpha: "XCD",
    currency_code_numeric: "951",
    dial_code: "1",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:SH",
    iso_code: "KN",
  },
  {
    country_name: "Trinidad and Tobago",
    country_code_alpha: "TTO",
    country_code_numeric: "780",
    currency_code_alpha: "TTD",
    currency_code_numeric: "780",
    dial_code: "1",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:TN",
    iso_code: "TT",
  },
  {
    country_name: "Uzbekistan",
    country_code_alpha: "UZB",
    country_code_numeric: "860",
    currency_code_alpha: "UZS",
    currency_code_numeric: "860",
    dial_code: "998",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:UY",
    iso_code: "UZ",
  },
  {
    country_name: "British Indian Ocean Territory",
    country_code_alpha: "IOT",
    country_code_numeric: "86",
    currency_code_alpha: "GBP",
    currency_code_numeric: "826",
    dial_code: "246",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:BR",
    iso_code: "IO",
  },
  {
    country_name: "Vatican City",
    country_code_alpha: "VAT",
    country_code_numeric: "336",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "379",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:VU",
    iso_code: "VA",
  },
  {
    country_name: "Libya",
    country_code_alpha: "LBY",
    country_code_numeric: "434",
    currency_code_alpha: "LYD",
    currency_code_numeric: "434",
    dial_code: "218",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:LR",
    iso_code: "LY",
  },
  {
    country_name: "Cayman Islands",
    country_code_alpha: "CYM",
    country_code_numeric: "136",
    currency_code_alpha: "KYD",
    currency_code_numeric: "136",
    dial_code: "1",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:CA",
    iso_code: "KY",
  },
  {
    country_name: "Wallis and Futuna",
    country_code_alpha: "WLF",
    country_code_numeric: "876",
    currency_code_alpha: "XPF",
    currency_code_numeric: "953",
    dial_code: "681",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:VG",
    iso_code: "WF",
  },
  {
    country_name: "Guadeloupe",
    country_code_alpha: "GLP",
    country_code_numeric: "312",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "590",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:GD",
    iso_code: "GP",
  },
  {
    country_name: "Antigua and Barbuda",
    country_code_alpha: "ATG",
    country_code_numeric: "28",
    currency_code_alpha: "XCD",
    currency_code_numeric: "951",
    dial_code: "1",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:AG",
    iso_code: "AG",
  },
  {
    country_name: "Peru",
    country_code_alpha: "PER",
    country_code_numeric: "604",
    currency_code_alpha: "PEN",
    currency_code_numeric: "604",
    dial_code: "51",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:PY",
    iso_code: "PE",
  },
  {
    country_name: "Uruguay",
    country_code_alpha: "URY",
    country_code_numeric: "858",
    currency_code_alpha: "UYU",
    currency_code_numeric: "858",
    dial_code: "598",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:UM",
    iso_code: "UY",
  },
  {
    country_name: "Lithuania",
    country_code_alpha: "LTU",
    country_code_numeric: "440",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "370",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:LI",
    iso_code: "LT",
  },
  {
    country_name: "Palestine, State of",
    country_code_alpha: "PSE",
    country_code_numeric: "275",
    currency_code_alpha: "ILS",
    currency_code_numeric: "376",
    dial_code: "970",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:PW",
    iso_code: "PS",
  },
  {
    country_name: "Germany",
    country_code_alpha: "DEU",
    country_code_numeric: "276",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "49",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:GE",
    iso_code: "DE",
  },
  {
    country_name: "Georgia",
    country_code_alpha: "GEO",
    country_code_numeric: "268",
    currency_code_alpha: "GEL",
    currency_code_numeric: "268",
    dial_code: "995",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:GM",
    iso_code: "GE",
  },
  {
    country_name: "Saint Pierre and Miquelon",
    country_code_alpha: "SPM",
    country_code_numeric: "666",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "508",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:MF",
    iso_code: "PM",
  },
  {
    country_name: "Timor-Leste",
    country_code_alpha: "TLS",
    country_code_numeric: "626",
    currency_code_alpha: "USD",
    currency_code_numeric: "840",
    dial_code: "670",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:TG",
    iso_code: "TL",
  },
  {
    country_name: "Montenegro",
    country_code_alpha: "MNE",
    country_code_numeric: "499",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "382",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:MN",
    iso_code: "ME",
  },
  {
    country_name: "Jordan",
    country_code_alpha: "JOR",
    country_code_numeric: "400",
    currency_code_alpha: "JOD",
    currency_code_numeric: "400",
    dial_code: "962",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:JE",
    iso_code: "JO",
  },
  {
    country_name: "Estonia",
    country_code_alpha: "EST",
    country_code_numeric: "233",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "372",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:ER",
    iso_code: "EE",
  },
  {
    country_name: "Nepal",
    country_code_alpha: "NPL",
    country_code_numeric: "524",
    currency_code_alpha: "NPR",
    currency_code_numeric: "524",
    dial_code: "977",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:NR",
    iso_code: "NP",
  },
  {
    country_name: "Burkina Faso",
    country_code_alpha: "BFA",
    country_code_numeric: "854",
    currency_code_alpha: "BIF",
    currency_code_numeric: "108",
    dial_code: "226",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:BG",
    iso_code: "BF",
  },
  {
    country_name: "Angola",
    country_code_alpha: "AGO",
    country_code_numeric: "24",
    currency_code_alpha: "AOA",
    currency_code_numeric: "24",
    dial_code: "244",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:AO",
    iso_code: "AO",
  },
  {
    country_name: "Maldives",
    country_code_alpha: "MDV",
    country_code_numeric: "462",
    currency_code_alpha: "MVR",
    currency_code_numeric: "462",
    dial_code: "960",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:MY",
    iso_code: "MV",
  },
  {
    country_name: "Réunion",
    country_code_alpha: "REU",
    country_code_numeric: "638",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "262",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:QA",
    iso_code: "RE",
  },
  {
    country_name: "United Kingdom",
    country_code_alpha: "GBR",
    country_code_numeric: "826",
    currency_code_alpha: "GBP",
    currency_code_numeric: "826",
    dial_code: "44",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:GB",
    iso_code: "GB",
  },
  {
    country_name: "Sudan",
    country_code_alpha: "SDN",
    country_code_numeric: "729",
    currency_code_alpha: "SDG",
    currency_code_numeric: "729",
    dial_code: "249",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:SD",
    iso_code: "SD",
  },
  {
    country_name: "Cuba",
    country_code_alpha: "CUB",
    country_code_numeric: "192",
    currency_code_alpha: "CUP",
    currency_code_numeric: "192",
    dial_code: "53",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:HR",
    iso_code: "CU",
  },
  {
    country_name: "Ireland",
    country_code_alpha: "IRL",
    country_code_numeric: "372",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "353",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:IQ",
    iso_code: "IE",
  },
  {
    country_name: "Venezuela",
    country_code_alpha: "VEN",
    country_code_numeric: "862",
    currency_code_alpha: "VEF",
    currency_code_numeric: "862",
    dial_code: "58",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:VE",
    iso_code: "VE",
  },
  {
    country_name: "Congo, Democratic Republic of the",
    country_code_alpha: "COD",
    country_code_numeric: "180",
    currency_code_alpha: "CDF",
    currency_code_numeric: "976",
    dial_code: "243",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:CG",
    iso_code: "CD",
  },
  {
    country_name: "Oman",
    country_code_alpha: "OMN",
    country_code_numeric: "512",
    currency_code_alpha: "OMR",
    currency_code_numeric: "512",
    dial_code: "968",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:NO",
    iso_code: "OM",
  },
  {
    country_name: "Latvia",
    country_code_alpha: "LVA",
    country_code_numeric: "428",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "371",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:LA",
    iso_code: "LV",
  },
  {
    country_name: "Austria",
    country_code_alpha: "AUT",
    country_code_numeric: "40",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "43",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:AT",
    iso_code: "AT",
  },
  {
    country_name: "Chad",
    country_code_alpha: "TCD",
    country_code_numeric: "148",
    currency_code_alpha: "XAF",
    currency_code_numeric: "950",
    dial_code: "235",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:CF",
    iso_code: "TD",
  },
  {
    country_name: "Bahamas",
    country_code_alpha: "BHS",
    country_code_numeric: "44",
    currency_code_alpha: "BSD",
    currency_code_numeric: "44",
    dial_code: "1",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:BS",
    iso_code: "BS",
  },
  {
    country_name: "Malaysia",
    country_code_alpha: "MYS",
    country_code_numeric: "458",
    currency_code_alpha: "MYR",
    currency_code_numeric: "458",
    dial_code: "60",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:MW",
    iso_code: "MY",
  },
  {
    country_name: "Comoros",
    country_code_alpha: "COM",
    country_code_numeric: "174",
    currency_code_alpha: "COM",
    currency_code_numeric: "174",
    dial_code: "269",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:CO",
    iso_code: "KM",
  },
  {
    country_name: "Zimbabwe",
    country_code_alpha: "ZWE",
    country_code_numeric: "716",
    currency_code_alpha: "ZWD",
    currency_code_numeric: "716",
    dial_code: "263",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:YE",
    iso_code: "ZW",
  },
  {
    country_name: "Saint Lucia",
    country_code_alpha: "LCA",
    country_code_numeric: "662",
    currency_code_alpha: "XCD",
    currency_code_numeric: "951",
    dial_code: "1",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:KN",
    iso_code: "LC",
  },
  {
    country_name: "Eritrea",
    country_code_alpha: "ERI",
    country_code_numeric: "232",
    currency_code_alpha: "ERN",
    currency_code_numeric: "232",
    dial_code: "291",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:GQ",
    iso_code: "ER",
  },
  {
    country_name: "Madagascar",
    country_code_alpha: "MDG",
    country_code_numeric: "450",
    currency_code_alpha: "MGA",
    currency_code_numeric: "450",
    dial_code: "261",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:MO",
    iso_code: "MG",
  },
  {
    country_name: "Japan",
    country_code_alpha: "JPN",
    country_code_numeric: "392",
    currency_code_alpha: "JPY",
    currency_code_numeric: "392",
    dial_code: "81",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:JM",
    iso_code: "JP",
  },
  {
    country_name: "French Polynesia",
    country_code_alpha: "PYF",
    country_code_numeric: "258",
    currency_code_alpha: "XPF",
    currency_code_numeric: "953",
    dial_code: "689",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:GF",
    iso_code: "PF",
  },
  {
    country_name: "Croatia",
    country_code_alpha: "HRV",
    country_code_numeric: "191",
    currency_code_alpha: "HRK",
    currency_code_numeric: "191",
    dial_code: "385",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:CI",
    iso_code: "HR",
  },
  {
    country_name: "Benin",
    country_code_alpha: "BEN",
    country_code_numeric: "204",
    currency_code_alpha: "XOF",
    currency_code_numeric: "952",
    dial_code: "229",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:BJ",
    iso_code: "BJ",
  },
  {
    country_name: "Azerbaijan",
    country_code_alpha: "AZE",
    country_code_numeric: "31",
    currency_code_alpha: "AZN",
    currency_code_numeric: "31",
    dial_code: "994",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:AZ",
    iso_code: "AZ",
  },
  {
    country_name: "Guam",
    country_code_alpha: "GUM",
    country_code_numeric: "316",
    currency_code_alpha: "USD",
    currency_code_numeric: "840",
    dial_code: "1",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:GP",
    iso_code: "GU",
  },
  {
    country_name: "Belarus",
    country_code_alpha: "BLR",
    country_code_numeric: "112",
    currency_code_alpha: "BYN",
    currency_code_numeric: "112",
    dial_code: "375",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:BY",
    iso_code: "BY",
  },
  {
    country_name: "Christmas Island",
    country_code_alpha: "CXR",
    country_code_numeric: "162",
    currency_code_alpha: "AUD",
    currency_code_numeric: "36",
    dial_code: "61",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:CN",
    iso_code: "CX",
  },
  {
    country_name: "Serbia",
    country_code_alpha: "SRB",
    country_code_numeric: "688",
    currency_code_alpha: "RSD",
    currency_code_numeric: "688",
    dial_code: "381",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:SN",
    iso_code: "RS",
  },
  {
    country_name: "Canada",
    country_code_alpha: "CAN",
    country_code_numeric: "124",
    currency_code_alpha: "CAD",
    currency_code_numeric: "124",
    dial_code: "1",
    region: "North America",
    iso_3166_2: "ISO 3166-2:CM",
    iso_code: "CA",
  },
  {
    country_name: "Martinique",
    country_code_alpha: "MTQ",
    country_code_numeric: "474",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "596",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:MH",
    iso_code: "MQ",
  },
  {
    country_name: "Congo",
    country_code_alpha: "COG",
    country_code_numeric: "178",
    currency_code_alpha: "CDF",
    currency_code_numeric: "976",
    dial_code: "242",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:KM",
    iso_code: "CG",
  },
  {
    country_name: "Anguilla",
    country_code_alpha: "AIA",
    country_code_numeric: "660",
    currency_code_alpha: "XCD",
    currency_code_numeric: "951",
    dial_code: "1",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:AI",
    iso_code: "AI",
  },
  {
    country_name: "San Marino",
    country_code_alpha: "SMR",
    country_code_numeric: "674",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "378",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:WS",
    iso_code: "SM",
  },
  {
    country_name: "Fiji",
    country_code_alpha: "FJI",
    country_code_numeric: "242",
    currency_code_alpha: "FJD",
    currency_code_numeric: "242",
    dial_code: "679",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:FO",
    iso_code: "FJ",
  },
  {
    country_name: "Antarctica",
    country_code_alpha: "ATA",
    country_code_numeric: "10",
    currency_code_alpha: "-",
    currency_code_numeric: "0",
    dial_code: "-",
    region: "Antarctica",
    iso_3166_2: "ISO 3166-2:AQ",
    iso_code: "AQ",
  },
  {
    country_name: "Poland",
    country_code_alpha: "POL",
    country_code_numeric: "616",
    currency_code_alpha: "PLN",
    currency_code_numeric: "616",
    dial_code: "48",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:PN",
    iso_code: "PL",
  },
  {
    country_name: "Qatar",
    country_code_alpha: "QAT",
    country_code_numeric: "634",
    currency_code_alpha: "QAR",
    currency_code_numeric: "634",
    dial_code: "974",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:PR",
    iso_code: "QA",
  },
  {
    country_name: "Mozambique",
    country_code_alpha: "MOZ",
    country_code_numeric: "508",
    currency_code_alpha: "MZN",
    currency_code_numeric: "508",
    dial_code: "258",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:MA",
    iso_code: "MZ",
  },
  {
    country_name: "Honduras",
    country_code_alpha: "HND",
    country_code_numeric: "340",
    currency_code_alpha: "HNL",
    currency_code_numeric: "340",
    dial_code: "504",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:VA",
    iso_code: "HN",
  },
  {
    country_name: "Guyana",
    country_code_alpha: "GUY",
    country_code_numeric: "328",
    currency_code_alpha: "GYD",
    currency_code_numeric: "328",
    dial_code: "592",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:GW",
    iso_code: "GY",
  },
  {
    country_name: "Kuwait",
    country_code_alpha: "KWT",
    country_code_numeric: "414",
    currency_code_alpha: "KWD",
    currency_code_numeric: "414",
    dial_code: "965",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:KR",
    iso_code: "KW",
  },
  {
    country_name: "Macao",
    country_code_alpha: "MAC",
    country_code_numeric: "446",
    currency_code_alpha: "MOP",
    currency_code_numeric: "446",
    dial_code: "853",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:LU",
    iso_code: "MO",
  },
  {
    country_name: "Cocos (Keeling) Islands",
    country_code_alpha: "CCK",
    country_code_numeric: "166",
    currency_code_alpha: "AUD",
    currency_code_numeric: "36",
    dial_code: "61",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:CX",
    iso_code: "CC",
  },
  {
    country_name: "Tokelau",
    country_code_alpha: "TKL",
    country_code_numeric: "772",
    currency_code_alpha: "NZD",
    currency_code_numeric: "554",
    dial_code: "690",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:TO",
    iso_code: "TK",
  },
  {
    country_name: "Denmark",
    country_code_alpha: "DNK",
    country_code_numeric: "208",
    currency_code_alpha: "DKK",
    currency_code_numeric: "208",
    dial_code: "45",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:CZ",
    iso_code: "DK",
  },
  {
    country_name: "Australia",
    country_code_alpha: "AUS",
    country_code_numeric: "36",
    currency_code_alpha: "AUD",
    currency_code_numeric: "36",
    dial_code: "61",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:AU",
    iso_code: "AU",
  },
  {
    country_name: "Mexico",
    country_code_alpha: "MEX",
    country_code_numeric: "484",
    currency_code_alpha: "MXN",
    currency_code_numeric: "484",
    dial_code: "52",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:YT",
    iso_code: "MX",
  },
  {
    country_name: "Ethiopia",
    country_code_alpha: "ETH",
    country_code_numeric: "231",
    currency_code_alpha: "ETB",
    currency_code_numeric: "231",
    dial_code: "251",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:SZ",
    iso_code: "ET",
  },
  {
    country_name: "Marshall Islands",
    country_code_alpha: "MHL",
    country_code_numeric: "584",
    currency_code_alpha: "USD",
    currency_code_numeric: "840",
    dial_code: "692",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:MT",
    iso_code: "MH",
  },
  {
    country_name: "United Arab Emirates",
    country_code_alpha: "ARE",
    country_code_numeric: "784",
    currency_code_alpha: "AED",
    currency_code_numeric: "784",
    dial_code: "971",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:AE",
    iso_code: "AE",
  },
  {
    country_name: "Vietnam",
    country_code_alpha: "VNM",
    country_code_numeric: "704",
    currency_code_alpha: "VND",
    currency_code_numeric: "704",
    dial_code: "84",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:VN",
    iso_code: "VN",
  },
  {
    country_name: "Moldova, Republic of",
    country_code_alpha: "MDA",
    country_code_numeric: "498",
    currency_code_alpha: "MDL",
    currency_code_numeric: "498",
    dial_code: "373",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:FM",
    iso_code: "MD",
  },
  {
    country_name: "Cook Islands",
    country_code_alpha: "COK",
    country_code_numeric: "184",
    currency_code_alpha: "NZD",
    currency_code_numeric: "554",
    dial_code: "682",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:CD",
    iso_code: "CK",
  },
  {
    country_name: "Albania",
    country_code_alpha: "ALB",
    country_code_numeric: "8",
    currency_code_alpha: "ALL",
    currency_code_numeric: "8",
    dial_code: "355",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:AL",
    iso_code: "AL",
  },
  {
    country_name: "Turkmenistan",
    country_code_alpha: "TKM",
    country_code_numeric: "795",
    currency_code_alpha: "TMT",
    currency_code_numeric: "795",
    dial_code: "993",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:TC",
    iso_code: "TM",
  },
  {
    country_name: "Sint Maarten",
    country_code_alpha: "SXM",
    country_code_numeric: "534",
    currency_code_alpha: "ANG",
    currency_code_numeric: "532",
    dial_code: "1",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:SX",
    iso_code: "SX",
  },
  {
    country_name: "Grenada",
    country_code_alpha: "GRD",
    country_code_numeric: "308",
    currency_code_alpha: "XCD",
    currency_code_numeric: "951",
    dial_code: "1",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:GL",
    iso_code: "GD",
  },
  {
    country_name: "Philippines",
    country_code_alpha: "PHL",
    country_code_numeric: "608",
    currency_code_alpha: "PHP",
    currency_code_numeric: "608",
    dial_code: "63",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:PE",
    iso_code: "PH",
  },
  {
    country_name: "Bonaire, Sint Eustatius and Saba",
    country_code_alpha: "BES",
    country_code_numeric: "530",
    currency_code_alpha: "USD",
    currency_code_numeric: "840",
    dial_code: "599",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:BO",
    iso_code: "BQ",
  },
  {
    country_name: "Senegal",
    country_code_alpha: "SEN",
    country_code_numeric: "686",
    currency_code_alpha: "XOF",
    currency_code_numeric: "952",
    dial_code: "221",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:SA",
    iso_code: "SN",
  },
  {
    country_name: "Dominica",
    country_code_alpha: "DMA",
    country_code_numeric: "212",
    currency_code_alpha: "XCD",
    currency_code_numeric: "951",
    dial_code: "1",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:DJ",
    iso_code: "DM",
  },
  {
    country_name: "Heard Island and McDonald Islands",
    country_code_alpha: "HMD",
    country_code_numeric: "334",
    currency_code_alpha: "AUD",
    currency_code_numeric: "36",
    dial_code: "61",
    region: "Antarctica",
    iso_3166_2: "ISO 3166-2:HT",
    iso_code: "HM",
  },
  {
    country_name: "Mayotte",
    country_code_alpha: "MYT",
    country_code_numeric: "175",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "269",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:MU",
    iso_code: "YT",
  },
  {
    country_name: "Aruba",
    country_code_alpha: "ABW",
    country_code_numeric: "533",
    currency_code_alpha: "AWG",
    currency_code_numeric: "533",
    dial_code: "297",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:AW",
    iso_code: "AW",
  },
  {
    country_name: "Malawi",
    country_code_alpha: "MW",
    country_code_numeric: "454",
    currency_code_alpha: "MWK",
    currency_code_numeric: "454",
    dial_code: "265",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:MG",
    iso_code: "MW",
  },
  {
    country_name: "Pitcairn",
    country_code_alpha: "PCN",
    country_code_numeric: "612",
    currency_code_alpha: "NZD",
    currency_code_numeric: "554",
    dial_code: "64",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:PH",
    iso_code: "PN",
  },
  {
    country_name: "Slovenia",
    country_code_alpha: "SVN",
    country_code_numeric: "705",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "386",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:SI",
    iso_code: "SI",
  },
  {
    country_name: "Tonga",
    country_code_alpha: "TON",
    country_code_numeric: "776",
    currency_code_alpha: "TOP",
    currency_code_numeric: "776",
    dial_code: "676",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:TT",
    iso_code: "TO",
  },
  {
    country_name: "Kiribati",
    country_code_alpha: "KIR",
    country_code_numeric: "296",
    currency_code_alpha: "AUD",
    currency_code_numeric: "36",
    dial_code: "686",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:KE",
    iso_code: "KI",
  },
  {
    country_name: "Pakistan",
    country_code_alpha: "PAK",
    country_code_numeric: "586",
    currency_code_alpha: "PKR",
    currency_code_numeric: "586",
    dial_code: "92",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:OM",
    iso_code: "PK",
  },
  {
    country_name: "Kenya",
    country_code_alpha: "KEN",
    country_code_numeric: "404",
    currency_code_alpha: "KES",
    currency_code_numeric: "404",
    dial_code: "254",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:KZ",
    iso_code: "KE",
  },
  {
    country_name: "Egypt",
    country_code_alpha: "EGY",
    country_code_numeric: "818",
    currency_code_alpha: "EGP",
    currency_code_numeric: "818",
    dial_code: "20",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:EC",
    iso_code: "EG",
  },
  {
    country_name: "Dominican Republic",
    country_code_alpha: "DOM",
    country_code_numeric: "214",
    currency_code_alpha: "DOP",
    currency_code_numeric: "214",
    dial_code: "1",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:DM",
    iso_code: "DO",
  },
  {
    country_name: "Sierra Leone",
    country_code_alpha: "SLE",
    country_code_numeric: "694",
    currency_code_alpha: "SLL",
    currency_code_numeric: "694",
    dial_code: "232",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:SC",
    iso_code: "SL",
  },
  {
    country_name: "Hungary",
    country_code_alpha: "HUN",
    country_code_numeric: "348",
    currency_code_alpha: "HUF",
    currency_code_numeric: "348",
    dial_code: "36",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:HK",
    iso_code: "HU",
  },
  {
    country_name: "Syria",
    country_code_alpha: "SYR",
    country_code_numeric: "760",
    currency_code_alpha: "SYP",
    currency_code_numeric: "760",
    dial_code: "963",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:TW",
    iso_code: "SY",
  },
  {
    country_name: "Singapore",
    country_code_alpha: "SGP",
    country_code_numeric: "702",
    currency_code_alpha: "SGD",
    currency_code_numeric: "702",
    dial_code: "65",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:SL",
    iso_code: "SG",
  },
  {
    country_name: "Equatorial Guinea",
    country_code_alpha: "GNQ",
    country_code_numeric: "226",
    currency_code_alpha: "XAF",
    currency_code_numeric: "950",
    dial_code: "240",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:SV",
    iso_code: "GQ",
  },
  {
    country_name: "El Salvador",
    country_code_alpha: "SLV",
    country_code_numeric: "222",
    currency_code_alpha: "SVC",
    currency_code_numeric: "222",
    dial_code: "503",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:EG",
    iso_code: "SV",
  },
  {
    country_name: "Iraq",
    country_code_alpha: "IRQ",
    country_code_numeric: "368",
    currency_code_alpha: "IQD",
    currency_code_numeric: "368",
    dial_code: "964",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:IR",
    iso_code: "IQ",
  },
  {
    country_name: "Falkland Islands (Malvinas)",
    country_code_alpha: "FLK",
    country_code_numeric: "238",
    currency_code_alpha: "GBP",
    currency_code_numeric: "826",
    dial_code: "500",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:ET",
    iso_code: "FK",
  },
  {
    country_name: "Gibraltar",
    country_code_alpha: "GIB",
    country_code_numeric: "292",
    currency_code_alpha: "GIP",
    currency_code_numeric: "292",
    dial_code: "350",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:GH",
    iso_code: "GI",
  },
  {
    country_name: "Mongolia",
    country_code_alpha: "MNG",
    country_code_numeric: "496",
    currency_code_alpha: "MNT",
    currency_code_numeric: "496",
    dial_code: "976",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:MC",
    iso_code: "MN",
  },
  {
    country_name: "Lao People's Democratic Republic",
    country_code_alpha: "LAO",
    country_code_numeric: "418",
    currency_code_alpha: "LAK",
    currency_code_numeric: "418",
    dial_code: "856",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:KG",
    iso_code: "LA",
  },
  {
    country_name: "Cabo Verde",
    country_code_alpha: "CPV",
    country_code_numeric: "132",
    currency_code_alpha: "CVE",
    currency_code_numeric: "132",
    dial_code: "238",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:BI",
    iso_code: "CV",
  },
  {
    country_name: "Svalbard and Jan Mayen",
    country_code_alpha: "SJM",
    country_code_numeric: "744",
    currency_code_alpha: "NOK",
    currency_code_numeric: "578",
    dial_code: "47",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:SJ",
    iso_code: "SJ",
  },
  {
    country_name: "Chile",
    country_code_alpha: "CHL",
    country_code_numeric: "152",
    currency_code_alpha: "CLP",
    currency_code_numeric: "152",
    dial_code: "56",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:TD",
    iso_code: "CL",
  },
  {
    country_name: "Palau",
    country_code_alpha: "PLW",
    country_code_numeric: "585",
    currency_code_alpha: "USD",
    currency_code_numeric: "840",
    dial_code: "680",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:PK",
    iso_code: "PW",
  },
  {
    country_name: "Sweden",
    country_code_alpha: "SWE",
    country_code_numeric: "752",
    currency_code_alpha: "SEK",
    currency_code_numeric: "752",
    dial_code: "46",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:CH",
    iso_code: "SE",
  },
  {
    country_name: "Saint Barthélemy",
    country_code_alpha: "BTH",
    country_code_numeric: "652",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "590",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:RW",
    iso_code: "BL",
  },
  {
    country_name: "Kyrgyzstan",
    country_code_alpha: "KGZ",
    country_code_numeric: "417",
    currency_code_alpha: "KGS",
    currency_code_numeric: "417",
    dial_code: "996",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:KW",
    iso_code: "KG",
  },
  {
    country_name: "South Africa",
    country_code_alpha: "ZAF",
    country_code_numeric: "710",
    currency_code_alpha: "ZAR",
    currency_code_numeric: "710",
    dial_code: "27",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:ZA",
    iso_code: "ZA",
  },
  {
    country_name: "Luxembourg",
    country_code_alpha: "LUX",
    country_code_numeric: "442",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "352",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:LT",
    iso_code: "LU",
  },
  {
    country_name: "Bouvet Island",
    country_code_alpha: "BVT",
    country_code_numeric: "74",
    currency_code_alpha: "NOK",
    currency_code_numeric: "578",
    dial_code: "47",
    region: "Antarctica",
    iso_3166_2: "ISO 3166-2:BW",
    iso_code: "BV",
  },
  {
    country_name: "Cyprus",
    country_code_alpha: "CYP",
    country_code_numeric: "196",
    currency_code_alpha: "CYP",
    currency_code_numeric: "196",
    dial_code: "357",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:CW",
    iso_code: "CY",
  },
  {
    country_name: "Namibia",
    country_code_alpha: "NAM",
    country_code_numeric: "516",
    currency_code_alpha: "NAD",
    currency_code_numeric: "516",
    dial_code: "264",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:MM",
    iso_code: "NA",
  },
  {
    country_name: "Somalia",
    country_code_alpha: "SOM",
    country_code_numeric: "706",
    currency_code_alpha: "SOS",
    currency_code_numeric: "706",
    dial_code: "252",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:SO",
    iso_code: "SO",
  },
  {
    country_name: "Iceland",
    country_code_alpha: "ISL",
    country_code_numeric: "352",
    currency_code_alpha: "ISK",
    currency_code_numeric: "352",
    dial_code: "354",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:HU",
    iso_code: "IS",
  },
  {
    country_name: "Czechia",
    country_code_alpha: "CZE",
    country_code_numeric: "203",
    currency_code_alpha: "CZK",
    currency_code_numeric: "203",
    dial_code: "420",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:CY",
    iso_code: "CZ",
  },
  {
    country_name: "Ecuador",
    country_code_alpha: "ECU",
    country_code_numeric: "218",
    currency_code_alpha: "USD",
    currency_code_numeric: "840",
    dial_code: "593",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:DO",
    iso_code: "EC",
  },
  {
    country_name: "Zambia",
    country_code_alpha: "ZMB",
    country_code_numeric: "894",
    currency_code_alpha: "ZMW",
    currency_code_numeric: "894",
    dial_code: "260",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:EH",
    iso_code: "ZM",
  },
  {
    country_name: "Switzerland",
    country_code_alpha: "CHE",
    country_code_numeric: "756",
    currency_code_alpha: "CHF",
    currency_code_numeric: "756",
    dial_code: "41",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:SY",
    iso_code: "CH",
  },
  {
    country_name: "Western Sahara",
    country_code_alpha: "ESH",
    country_code_numeric: "732",
    currency_code_alpha: "MAD",
    currency_code_numeric: "504",
    dial_code: "212",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:VI",
    iso_code: "EH",
  },
  {
    country_name: "Bahrain",
    country_code_alpha: "BHR",
    country_code_numeric: "48",
    currency_code_alpha: "BHD",
    currency_code_numeric: "48",
    dial_code: "973",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:BH",
    iso_code: "BH",
  },
  {
    country_name: "Djibouti",
    country_code_alpha: "DJI",
    country_code_numeric: "262",
    currency_code_alpha: "DJF",
    currency_code_numeric: "262",
    dial_code: "253",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:DK",
    iso_code: "DJ",
  },
  {
    country_name: "United States",
    country_code_alpha: "USA",
    country_code_numeric: "840",
    currency_code_alpha: "USD",
    currency_code_numeric: "840",
    dial_code: "1",
    region: "Americas",
    iso_3166_2: "ISO 3166-2:US",
    iso_code: "US",
  },
  {
    country_name: "Swaziland (now Eswatini)",
    country_code_alpha: "SWZ",
    country_code_numeric: "748",
    currency_code_alpha: "SZL",
    currency_code_numeric: "748",
    dial_code: "268",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:SE",
    iso_code: "SZ",
  },
  {
    country_name: "Slovakia",
    country_code_alpha: "SVK",
    country_code_numeric: "703",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "421",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:SK",
    iso_code: "SK",
  },
  {
    country_name: "French Southern Territories",
    country_code_alpha: "ATF",
    country_code_numeric: "260",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "262",
    region: "Antarctica",
    iso_3166_2: "ISO 3166-2:PF",
    iso_code: "TF",
  },
  {
    country_name: "Andorra",
    country_code_alpha: "AND",
    country_code_numeric: "20",
    currency_code_alpha: "EUR",
    currency_code_numeric: "978",
    dial_code: "376",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:AD",
    iso_code: "AD",
  },
  {
    country_name: "Vanuatu",
    country_code_alpha: "VUT",
    country_code_numeric: "548",
    currency_code_alpha: "VUV",
    currency_code_numeric: "548",
    dial_code: "678",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:UZ",
    iso_code: "VU",
  },
  {
    country_name: "Tuvalu",
    country_code_alpha: "TUV",
    country_code_numeric: "798",
    currency_code_alpha: "AUD",
    currency_code_numeric: "36",
    dial_code: "688",
    region: "Oceania",
    iso_3166_2: "ISO 3166-2:TV",
    iso_code: "TV",
  },
  {
    country_name: "Saudi Arabia",
    country_code_alpha: "SAU",
    country_code_numeric: "682",
    currency_code_alpha: "SAR",
    currency_code_numeric: "682",
    dial_code: "966",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:ST",
    iso_code: "SA",
  },
  {
    country_name: "Indonesia",
    country_code_alpha: "IDN",
    country_code_numeric: "360",
    currency_code_alpha: "IDR",
    currency_code_numeric: "360",
    dial_code: "62",
    region: "Asia",
    iso_3166_2: "ISO 3166-2:IN",
    iso_code: "ID",
  },
  {
    country_name: "Central African Republic",
    country_code_alpha: "CAF",
    country_code_numeric: "140",
    currency_code_alpha: "CFA",
    currency_code_numeric: "950",
    dial_code: "236",
    region: "Africa",
    iso_3166_2: "ISO 3166-2:KY",
    iso_code: "CF",
  },
  {
    country_name: "Romania",
    country_code_alpha: "ROU",
    country_code_numeric: "642",
    currency_code_alpha: "RON",
    currency_code_numeric: "642",
    dial_code: "40",
    region: "Europe",
    iso_3166_2: "ISO 3166-2:RE",
    iso_code: "RO",
  },
];

module.exports = { LocalizationCodeData };
